### PR TITLE
Feature/cv2 3991 cluster card

### PR DESCRIPTION
**Pull request by amoedoamorim**
## Description

Refactor SharedItemCard and WorkspaceItemCard into ClusterCard and use it for all lists.

References: CV2-3991

## Type of change

- [ ] Performance improvement and/or refactoring (non-breaking change that keeps existing functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Security mitigation or enhancement
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Automated test (add or update automated tests)

## How has this been tested?

Tested manually that things look good on lists and feeds. Working on unit tests while PR is up for review.

## Things to pay attention to during code review

No big deal in the code, some tweaks and lots of deleted code. Testing is the real challenge due to the huge number of props and permutations of them.

## Checklist

- [x] I have performed a self-review of my own code
- [x] I've made sure my branch is runnable and given good testing steps in the PR description
- [ ] I considered secure coding practices when writing this code. Any security concerns are noted above.
- [ ] I have commented my code in hard-to-understand areas, if any
- [ ] I have made needed changes to the README
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] If I implemented any new components, they are self-contained, their `propTypes` are declared and they use React Hooks and, if data-fetching is required, they use Relay Modern with fragment containers
- [ ] If my components involve user interaction - specifically button, text fields, or other inputs - I have added a [BEM-like class name](https://meedan.atlassian.net/wiki/spaces/ENG/pages/1327628289/Naming+conventions+for+interactive+elements) to the element that is interacted with
- [ ] To the best of my knowledge, any new styles are applied according to the design system
- [ ] If I added a new external dependency, I included a rationale for doing so and an estimate of the change in bundle size (e.g., checked in https://bundlephobia.com/)

### CODE REVIEW

**Review by caiosba — APPROVED** [review]
Great to see all these deleted files! <3

**Comment by caiosba** [comment]
I tested it locally also, and it works well!

**Comment by brianfleming** [comment]
whoa, take a look at that diff!
Screenshot 2024-06-04 at 11 07 04 AM

@amoedoamorim are you doing sorting separately?

**Comment by amoedoamorim** [comment]
> @amoedoamorim are you doing sorting separately?

Yeah, sorting will be handled in CV2-3924

**Review by brianfleming — APPROVED** [review]
Thanks for the sorting note @amoedoamorim excited to see this moving forward

**Comment by amoedoamorim** [comment]
Closing this PR in favor of a MORE EPIC one https://github.com/meedan/check-web/pull/1963

**Pull request closed without merging**
