### PR TITLE
Cv2 4136 timpani accessible yake keyword model 

### PR DESCRIPTION
**Pull request by ahmednasserswe**
## Description

to apply the changes that reflects the changes on CV2-4136-timpani-accessible-yake-keyword-model in Presto. Mainly return values' names. 

References: CV2-4136

## Type of change

- [ ] Performance improvement and/or refactoring (non-breaking change that keeps existing functionality)
- [✔️](https://emojipedia.org/check-mark) Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Security mitigation or enhancement
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Automated test (add or update automated tests)

## How has this been tested?

Locally + unit and integration tests

## Things to pay attention to during code review

Purposely, first commit to this PR is expected to fail. 

## Checklist

- [ ] I have performed a self-review of my own code
- [ ] I've made sure my branch is runnable and given good testing steps in the PR description
- [ ] I considered secure coding practices when writing this code. Any security concerns are noted above.
- [ ] I have commented my code in hard-to-understand areas, if any
- [ ] I have made needed changes to the README
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I implemented any new components, they are self-contained, their `propTypes` are declared and they use React Hooks and, if data-fetching is required, they use Relay Modern with fragment containers
- [ ] If my components involve user interaction - specifically button, text fields, or other inputs - I have added a [BEM-like class name](https://meedan.atlassian.net/wiki/spaces/ENG/pages/1327628289/Naming+conventions+for+interactive+elements) to the element that is interacted with
- [ ] To the best of my knowledge, any new styles are applied according to the design system
- [ ] If I added a new external dependency, I included a rationale for doing so and an estimate of the change in bundle size (e.g., checked in https://bundlephobia.com/)

### CODE REVIEW

**Comment by caiosba** [comment]
@ahmednasserswe , I guess this addition is to run integration tests? feel free to assign for review once integration tests are passing

**Comment by ahmednasserswe** [comment]
I am working on this PR. My plan is the following 
I’ll make the changes needed on both Check-web and Alegre that reflects the changes we made on Presto (mainly chanigng “hash_value” to  “result”) (Cc. @Devin Gaffney) 

In order to know what changes needed, I’ll first create the PRs in both Alegre and Check-web and run the tests to see where they fail and see if there is some other changes needed other than “hash_value” to “results” . Later, I am going to fix the parts that fail.

**Comment by computermacgyver** [comment]
Thanks, @ahmednasserswe . A correction here, however. We wanted to verify the integration tests failed before the fix and that they pass after the fix. We should *not*, however, use the tests to determine where updates are needed. For that, please search across all code files in Alegre for `hash_value` and update where needed.

**Comment by computermacgyver** [comment]
We are adding yake keyword extraction to Presto. In the first instance it will be used by Timpani and *not* by Check. As such, we want this PR to simply run integration tests and ensure there is not a regression. We should *not* have any changes to the docker files or build scripts, however.

**Pull request closed without merging**
