### PR TITLE
Deprecating next/previous media item nav

### PR DESCRIPTION
**Pull request by dariusk**
This removes the `NextPreviousLinks` component from the header in the media item view. Also removing the unit tests that check for calculating sibling nav urls when `MediaPage` is rendered, since that was only needed for the `NextPreviousLinks` component.

The component, along with the helper function `getListUrlQueryAndIndex`, is still used in the `media/FeedItem.js`

image

CV2-3361

## Type of change

- [] Performance improvement and/or refactoring (non-breaking change that keeps existing functionality)
- [] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Automated test (add or update automated tests)

## How has this been tested?

Unit testing (actually lack of unit tests!) and confirming that the feature still works elsewhere, as in `FeedItem`.

## Checklist

- [X] I have performed a self-review of my own code
- [X] I've made sure my branch is runnable and given good testing steps in the PR description
- [ ] I have commented my code in hard-to-understand areas, if any
- [ ] I have made needed changes to the README
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [ ] If I implemented any new components, they are self-contained, their `propTypes` are declared and they use React Hooks and, if data-fetching is required, they use Relay Modern with fragment containers
- [ ] I have removed the /* eslint-disable @calm/react-intl/missing-attribute */ from any files I've worked on and added a `description` prop to all `<FormattedMessage />` components that were missing it.
- [X] To the best of my knowledge, any new styles are applied according to the design system
- [ ] If I added a new external dependency, I included a rationale for doing so and an estimate of the change in bundle size (e.g., checked in https://bundlephobia.com/)

### CODE REVIEW

**Review by brianfleming — APPROVED** [review]
oh so close:
Screenshot 2023-07-18 at 3 49 15 PM

**Comment by dariusk** [comment]
If we'd stuck to one line per prop we would have made it!

**Review by caiosba — COMMENTED** [review]
@dariusk please run the integration tests in this branch before merging, I think some tests can be affected by this change.

**Comment by dariusk** [comment]
@caiosba Good point! Adding now

**Comment by amoedoamorim** [comment]
@dariusk did this pass the integration tests? We have a couple of failed tests on develop that seem to relate to this ticket:

rspec './spec/integration_spec.rb[1:1:63:1]' # integration (chrome) web behaves like media should go from one item to another
rspec './spec/integration_spec.rb[1:1:64:1]' # integration (chrome) web behaves like media should go from one item to another

**Comment by dariusk** [comment]
@amoedoamorim Oops! I'll fix those (by deleting them). Completely forgot to check.

**Pull request merged**
