### PR TITLE
Card  Improvements [CV2-4887]

### PR DESCRIPTION
**Pull request by brianfleming**
## Description

First bit of feedback came in on the cards to make the unread status more prominent. This PR adds that as well as:
- Updates the sandbox to be more realistic and add other options
- Removes the duplicate cluster cards and gets down to one
- Added the ability to not have a description on cluster card, but have a fact-check link

References:  [CV2-4887](https://meedan.atlassian.net/browse/CV2-4887) and [CV2-4885](https://meedan.atlassian.net/browse/CV2-4885)

## Type of change

- [x] Performance improvement and/or refactoring (non-breaking change that keeps existing functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Security mitigation or enhancement
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Automated test (add or update automated tests)

## How has this been tested?

Sandbox

## Things to pay attention to during code review

not much

## Checklist

- [x] I have performed a self-review of my own code
- [x] I've made sure my branch is runnable and given good testing steps in the PR description
- [x] I considered secure coding practices when writing this code. Any security concerns are noted above.
- [x] I have commented my code in hard-to-understand areas, if any
- [ ] I have made needed changes to the README
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I implemented any new components, they are self-contained, their `propTypes` are declared and they use React Hooks and, if data-fetching is required, they use Relay Modern with fragment containers
- [ ] If my components involve user interaction - specifically button, text fields, or other inputs - I have added a [BEM-like class name](https://meedan.atlassian.net/wiki/spaces/ENG/pages/1327628289/Naming+conventions+for+interactive+elements) to the element that is interacted with
- [x] To the best of my knowledge, any new styles are applied according to the design system
- [ ] If I added a new external dependency, I included a rationale for doing so and an estimate of the change in bundle size (e.g., checked in https://bundlephobia.com/)

[CV2-4887]: https://meedan.atlassian.net/browse/CV2-4887?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CV2-4885]: https://meedan.atlassian.net/browse/CV2-4885?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by amoedoamorim** [comment]
@brianfleming is this still a draft or ready for review?

**Comment by brianfleming** [comment]
@amoedoamorim as I mentioned on the call I need some help with these changes because of things I discovered while updating the unread status coloring. Some of them are just updates to the sandbox, but one might be a merge issue when we brought in the cards. So can you help on this branch with:

### Article Card
- The Date that is shown in the right side should be the Last Updated information, right now it mentions published, it should be the same as the Cluster Card Date
#### Incorrect:
Screenshot 2024-07-09 at 1 46 19 PM

#### Correct:
Screenshot 2024-07-09 at 1 46 24 PM

- I added a new "Published" Toggle to the article card in the sandbox, right now its hiding the published status icon. Instead it should toggle between published and unpublished, just like the cluster card when the variant is fact-check
- Tags, I added a toggle so we can see Article cards with tags or 0 tags, however, when the article card is in a shared feed, the tags should be hidden. I didn't know the cleanest way to do that in the sandbox

### Cluster Card
- When `Shared Feed == true` and `Fact-Check == false` the fact check area in the right side should be hidden. This translates to a shared feed that is not sharing fact-checks

### Both Cards
- the Published status icon should show the date it was published in the tooltip, if the item is published, as seen in designs:
Screenshot 2024-07-09 at 1 44 01 PM

**Comment by brianfleming** [comment]
> @brianfleming is this still in progress?

I think its ready for you now, let me know if the comment i added it clear, also happy to jump on a call to explain

**Comment by amoedoamorim** [comment]
Yeah, all clear, thanks. Working on it!

**Comment by amoedoamorim** [comment]
> When Shared Feed == true and Fact-Check == false the fact check area in the right side should be hidden. This translates to a shared feed that is not sharing fact-checks

Should this state display the `no fact-check` label?
Screenshot from 2024-07-09 18-04-15

**Comment by brianfleming** [comment]
> > When Shared Feed == true and Fact-Check == false the fact check area in the right side should be hidden. This translates to a shared feed that is not sharing fact-checks
> 
> Should this state display the `no fact-check` label? Screenshot from 2024-07-09 18-04-15

- No @amoedoamorim in this case (for shared feeds) it should just be hidden
- It should show "no fact-check" when (in this new articles world), there is no fact-check associated with the cluster. I am not sure if this is available yet from the API

**Comment by caiosba** [comment]
`It should show "no fact-check" when (in this new articles world), there is no fact-check associated with the cluster. I am not sure if this is available yet from the API`

@amoedoamorim @brianfleming if I'm understanding this correctly, for media clusters (`ProjectMedia`) this can be inferred from the `report_status` field, which can assume values `unpublished`, `published` or `paused`.

**Comment by brianfleming** [comment]
> 50d4fe1

Thinking about this more @amoedoamorim and @caiosba this is now directly overlapping with the ticket discussed this afternoon: https://meedan.atlassian.net/browse/CV2-4885

So we might just want to take care of that in this branch. So the bring that in to this discussion and summarize:

### Cluster Card in Shared Feed:
- **IF NOT** sharing fact checks: hide that area, and all that will be there is the date updated with its tooltip
- **IF YES** sharing fact checks we will see the count of fact-checks

### Cluster Card in Tipline Workspace list
- if no articles (fact-checks or explainers): output `no articles` in the style of the current `no fact-checks` this is a replacement and an extension to include checking for explainers
- if fact-check is present (regardless of number of explainers), output the fact-check summary component, the rating and publication status icon thing
- if explainers only, see https://meedan.atlassian.net/browse/CV2-4885 and output the count of explainers in the style of the count of fact-checks in a shared feed cluseter, just with the different icon

Hope this makes sense

**Comment by caiosba** [comment]
Makes sense to me and I think that the API already exposes all this data. @amoedoamorim  if you need help, please lmk.

**Comment by amoedoamorim** [comment]
Thanks Brian. Working on these bullets and CV2-4885 now in the current branch

**Comment by amoedoamorim** [comment]
@brianfleming I think I've addressed the requests in your comment and CV2-4885

**Comment by brianfleming** [comment]
@amoedoamorim I just pulled down and tried to startup and there are errors related to graphql and SearchResults.js
is there an API branch or changes you have not pushed i need?

**Comment by amoedoamorim** [comment]
Sorry, that's right! Just pushed the Check API changes to the `epic/CV2-4441-articles` branch

**Comment by brianfleming** [comment]
nice @amoedoamorim just two things:
1. can you help with the merge conflict, I think you know what the right choice there is better than me
2. the lists around the workspace look good and are behaving correctly, can you just do a pass on the sandbox so its a bit more accurate...for example, cluster card not in shared feed is missing the fact-check/article summary area:

Screenshot 2024-07-11 at 4 11 00 PM

**Comment by brianfleming** [comment]
ps. i added an API branch of the same name so we could verify tests

**Comment by amoedoamorim** [comment]
Sure, on it! I started dealing with the Sandbox then went on to other components and forgot to go back and re-check the Sandbox for sanity!

**Comment by amoedoamorim** [comment]
@brianfleming done resolving merge conflict and fixing sandbox. If you see my commit, I had to simplify that sandbox `listItemDataPointsFactCheck` handling because that was broken as it was, and we're really only interested in these two cases: no data points at all (workspace scenario) both data points (shared feed scenario)

**Comment by brianfleming** [comment]
> @brianfleming done resolving merge conflict and fixing sandbox. If you see my commit, I had to simplify that sandbox `listItemDataPointsFactCheck` handling because that was broken as it was, and we're really only interested in these two cases: no data points at all (workspace scenario) both data points (shared feed scenario)

Awesome, thanks @amoedoamorim there are still some improvements we can make to the sandbox, but i don't think its worth going overboard at this moment, the real goal is to make sure the lists are accurate. Thanks for you help on this, ready for review

**Review by amoedoamorim — APPROVED** [review]
:lgtm:

**Comment by brianfleming** [comment]
> :lgtm:



> :lgtm:

Sorry @amoedoamorim I included one additional change just now, can you just verify and let me know if its ok to merge?
I wanted to include the Articles concept in the ClusterCard, so I added a new Articles switch. Its disable "on" when in a shard feed because right now we only have the concept of fact-checks in shared feeds, so you can see the "empty" state of fact-checks with the other toggle.

Anyway, i promise I won't make any more changes to the PR so we can just merge on your say-so 🤞

**Review by amoedoamorim — APPROVED** [review]
:lgtm:

**Pull request merged**
