### PR TITLE
Header improvements and fix to long shared feed names

### PR DESCRIPTION
**Pull request by brianfleming**
## Description

- truncates long shared feed names in the tooltip where they are referenced on a custom list
- adds some missing shadow variables for tooltips
- some missing localization descriptions
- consolidates header styles amongst lists, folders, shared feeds, etc
- removes icons on the header area of items that no longer have icons in the side navigation
- removes header css file for shared feeds now that styles are combined for all headers
- Adds a subtitle for types of lists to match the designs of shared feeds

References: [CV2-3537](https://meedan.atlassian.net/browse/CV2-3537)

## Type of change

- [x] Performance improvement and/or refactoring (non-breaking change that keeps existing functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Automated test (add or update automated tests)

## How has this been tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can verify the changes. Please describe whether or not you implemented automated tests.

### AFTER Tooltip:
Screenshot 2023-08-07 at 1 55 52 PM

## Checklist

- [x] I have performed a self-review of my own code
- [x] I've made sure my branch is runnable and given good testing steps in the PR description
- [ ] I have commented my code in hard-to-understand areas, if any
- [ ] I have made needed changes to the README
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I implemented any new components, they are self-contained, their `propTypes` are declared and they use React Hooks and, if data-fetching is required, they use Relay Modern with fragment containers
- [x] I have removed the /* eslint-disable @calm/react-intl/missing-attribute */ from any files I've worked on and added a `description` prop to all `<FormattedMessage />` components that were missing it.
- [x] To the best of my knowledge, any new styles are applied according to the design system
- [ ] If I added a new external dependency, I included a rationale for doing so and an estimate of the change in bundle size (e.g., checked in https://bundlephobia.com/)

[CV2-3537]: https://meedan.atlassian.net/browse/CV2-3537?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by brianfleming** [comment]
@dariusk considering you are working on removing folders...to make things straightforward while I was working on this, changes in the PR also effect folder (like their list view titles, etc). So I *think* that it will be easier to review and merge this PR before your folder stuff. since then you are just removing code that this PR touches.  thoughts?

**Comment by dariusk** [comment]
@brianfleming Correct. I'll give it a review

**Review by dariusk — APPROVED** [review]
This all looks good, and the fix worked locally for me.

**Comment by brianfleming** [comment]
Thanks @dariusk 
now to the folders I say...Off with their heads!

off-with-their-head

**Pull request merged**
