### PR TITLE
Feature/Cv2-2899-custom-switch-component

### PR DESCRIPTION
**Pull request by danielevalverde**
## Description

Add Custom Switch component

References: CV2-2899

## Type of change

- [ ] Performance improvement and/or refactoring (non-breaking change that keeps existing functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Automated test (add or update automated tests)

## Checklist

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code in hard-to-understand areas, if any
- [ ] I have made needed changes to the README
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I implemented any new components, they are self-contained, their `propTypes` are declared and they use React Hooks and, if data-fetching is required, they use Relay Modern with fragment containers
- [ ] I have removed the /* eslint-disable @calm/react-intl/missing-attribute */ from any files I've worked on and added a `description` prop to all `<FormattedMessage />` components that were missing it.
- [ ] To the best of my knowledge, any new styles are applied according to the design system
- [ ] If I added a new external dependency, I included a rationale for doing so and an estimate of the change in bundle size (e.g., checked in https://bundlephobia.com/)

### CODE REVIEW

**Review by dariusk — APPROVED** [review]
Looks good! I've made a ticket for the future refactoring work, too.

**Comment by brianfleming** [comment]
@danielevalverde a heads up for you. I just merged [this PR](https://github.com/meedan/check-web/pull/1409) which moves the process forward to using css variables for colors instead of whats in `shared.js`. So you will need to go and replace the references in your branch. Let me know if I can answer any questions for you.

**Comment by brianfleming** [comment]
@dariusk @danielevalverde @amoedoamorim I have made some changes to this branch after we talked in order to show a path of how to override material ui styles while using the css modules approach.

Some things to note:
- I added a Switch.module.css file to do the styling.
- I changed the inject order of styles in order for our custom styles to be able to override material. See this documentation: [https://mui.com/system/styles/advanced/#css-injection-order](https://mui.com/system/styles/advanced/#css-injection-order) 
- In order to use the material ui class names, you have to keep them in the global scope inside of your locally scoped css module file. this is why you will see the `:global` css selector. Check out this discussion for some useful info: [https://stackoverflow.com/questions/46053422/how-does-local-class-work-in-css-modules](https://stackoverflow.com/questions/46053422/how-does-local-class-work-in-css-modules)

Let me know if anyone would like to discuss this approach

**Comment by brianfleming** [comment]
I just noticed an issue I missed while I was fixing some label positioning. There is a new console error related to these changes:

`Material-UI: You cannot use the jss and injectFirst props at the same time.`

which was added in order to override material styles in a stylesheet

Just a quick look it seems like it may affect the rtl vs ltr setting. But this needs a bit more investigation:

[https://mui.com/system/styles/advanced/#css-injection-order](https://mui.com/system/styles/advanced/#css-injection-order)

**Comment by brianfleming** [comment]
> Yeah it looks like we need to change the configuration where we set the rtl stuff in `src/web/index.js` - I'd follow the breadcrumbs here https://stackoverflow.com/a/59834184 (I can take a look tomorrow when I'm not traveling all day)

yeah, I think I got on the same path as you @dariusk thanks for the link. My last push seems to fix, no error, rtl layout looks good (see screenshot) and styles are applied

Screenshot 2023-04-19 at 11 35 41 AM

**Review by dariusk — APPROVED** [review]
Awesome, that last commit is pretty much exactly what I was envisioning.

**Comment by danielevalverde** [comment]
Thanks for all the help @brianfleming , @dariusk , @amoedoamorim :pray:

**Review by amoedoamorim — APPROVED** [review]

**Pull request merged**
