### PR TITLE
Misc change and Fixes after color updates

### PR DESCRIPTION
**Pull request by brianfleming**
## Description

- Fix some color references I missed before
- remove some old testing code for cards in the sandbox
- updating the slideout button to match design system
- update the media chip component to better work with line heights

## Type of change

- [x] Performance improvement and/or refactoring (non-breaking change that keeps existing functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Security mitigation or enhancement
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Automated test (add or update automated tests)

## How has this been tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can verify the changes. Please describe whether or not you implemented automated tests.

### BEFORE - note the changes in line height because the chip pushes lines up and down
Screenshot 2024-05-24 at 8 58 47 AM

### AFTER - the line height stays consistent
Screenshot 2024-05-29 at 11 11 59 AM

## Checklist

- [x] I have performed a self-review of my own code
- [x] I've made sure my branch is runnable and given good testing steps in the PR description
- [x] I considered secure coding practices when writing this code. Any security concerns are noted above.
- [x] I have commented my code in hard-to-understand areas, if any
- [ ] I have made needed changes to the README
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I implemented any new components, they are self-contained, their `propTypes` are declared and they use React Hooks and, if data-fetching is required, they use Relay Modern with fragment containers
- [ ] If my components involve user interaction - specifically button, text fields, or other inputs - I have added a [BEM-like class name](https://meedan.atlassian.net/wiki/spaces/ENG/pages/1327628289/Naming+conventions+for+interactive+elements) to the element that is interacted with
- [x] To the best of my knowledge, any new styles are applied according to the design system
- [ ] If I added a new external dependency, I included a rationale for doing so and an estimate of the change in bundle size (e.g., checked in https://bundlephobia.com/)

### CODE REVIEW

**Comment by brianfleming** [comment]
to the front-end team reviewers. This is just the random changes I mentioned yesterday. nothing too impactful, but wanted to get this in before switching to doing things like this on the epic branch

**Comment by brianfleming** [comment]
@amoedoamorim FYI: I removed the old testing card layout thing, so we can focus later reviews on your real stuff

**Comment by amoedoamorim** [comment]
Why does this PR diff shows code from Caio's and Dani's already merged PRs? :thinky:

**Review by amoedoamorim — APPROVED** [review]
:lgtm:

**Comment by brianfleming** [comment]
poor rebase command on my part I think @amoedoamorim

**Comment by amoedoamorim** [comment]
Looks like there's no conflicts, so should be good to go

**Pull request merged**
