### PR TITLE
Add PostCSS and CSS modules

### PR DESCRIPTION
**Pull request by brianfleming**
## Description

This PR is an alternate proposal but solving the same issues as seen in [CV2-2878](https://meedan.atlassian.net/browse/CV2-2878) 

CSS as a language has progressed a lot over the years and solutions such as sass were put in place to tackle its shortcomings have always been a popular choice. sass has grown and diverged from css becoming almost its own language. This PR shows an alternative by using PostCSS which is a processor that allows us to choose which forward looking features to use in css without deviating too much from the base language

Instead of repeating what other have said. Here are some links for the uninitiated:
- written in the context of vue, but still good [read on extensibility](https://zerotomastery.io/blog/postcss-vs-sass/)
- [bridging the gap](https://css-tricks.com/bridging-the-gap-between-css-and-javascript-css-modules-postcss-and-the-future-of-css/)
- there are a lot of other articles out there, google is your friend

References: [CV2-2878](https://meedan.atlassian.net/browse/CV2-2878)

## Type of change

- [x] Performance improvement and/or refactoring (non-breaking change that keeps existing functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Automated test (add or update automated tests)

## How has this been tested?

Manual teting

## Things to pay attention to during code review

There are a few goals wrapped up in [CV2-2878](https://meedan.atlassian.net/browse/CV2-2878) that have been discussed mostly around transitioning our css infrastructure to a more "traditional" layout to help non-engineers (designers) contribute more quickly to the codebase by writing "plain" css and interacting less with js which is more tricky for non engineers to avoid errors, as well as having the overall file structure easier to interpret, etc.

In the PR I put in some example usage just to highlight what is possible. Some things to note:

### General notes
- we are on webpack 4, and I wanted to keep the diff as small as possible, so this setup does not upgrade webpack, but it does upgrade some node packages to the "latest" version that still supports webpack 4
- the logic of the compiled css files are, the `main` chunk contains base styles for things like layout, typography, etc, things that do not change very often
- the `index` chunk contains any css from css modules (components) as well as any css loaded from npm modules (leaflet, etc)
- the `variables` chunk contains our `:root` variables (the replacement for `shared.js` sort of)
- I have chosen some "starter" postcss plugins that in the past I have found most useful to get the benefits of a language like sass. Such as nesting rules, color modification, for loops, mixins. 
- I have added some random color borders and backgrounds to a few elements in the dom to more easily see how to do certain things like: styling base html, that you can use nesting rules, how to use mixins, how to style css module components. Obviously these styles will be ripped out before merge.
- a benefit of this approach is since we did not have any css files before output in the dom we can leave existing code alone and slowly transition as we do development

### CSS modules
- I have enabled css modules that we can use for components. As you will see in the search component. Simply by naming the associated css file to include  [name]`.module.css` the compiled css is now locally scoped so we can not be worried about css conflicts
- if you do not name your css file as such ^, you get globally scoped which is what I did for the base index css and variables

### CSS variables
- you will now see that i am outputting css variables which we should use for color, typography, etc in the `:root` element. In a transition period away from material ui we will have to maintain two "variable" files, but I believe these variables don't change often enough for it to be a huge issue.
- before merge i would recommend just a basic sync between shared.js color and the new variables file.

## Checklist

- [x] I have performed a self-review of my own code
- [ ] I have commented my code in hard-to-understand areas, if any
- [ ] I have made needed changes to the README
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I implemented any new components, they are self-contained, their `propTypes` are declared and they use React Hooks and, if data-fetching is required, they use Relay Modern with fragment containers
- [ ] I have removed the /* eslint-disable @calm/react-intl/missing-attribute */ from any files I've worked on and added a `description` prop to all `<FormattedMessage />` components that were missing it.
- [ ] To the best of my knowledge, any new styles are applied according to the design system
- [ ] If I added a new external dependency, I included a rationale for doing so and an estimate of the change in bundle size (e.g., checked in https://bundlephobia.com/)

[CV2-2878]: https://meedan.atlassian.net/browse/CV2-2878?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CV2-2878]: https://meedan.atlassian.net/browse/CV2-2878?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by dariusk** [comment]
Love the look of this! For starters it is just really nice to see this in the file system:

image

Also love the non-globally-scoped CSS modules. And I prefer PostCSS to a precompiler too. I also did a check and it seems like the new chunking is working as expected.

Basically this is an enthusiastic thumbs-up from me!

**Comment by caiosba** [comment]
Thanks @brianfleming , this looks very good!

I have reviewed the changes and I appreciate the care you took to ensure that the implementation is consistent with the existing code architecture.

I tested it locally and it worked like a charm - I like the fact that you generate unique bundles like we do with the JavaScript files, it will help with caching issues on production.

Happy to approve when we have a final version - just remove the test code and styles, I guess (although I appreciate the border in Brazil flag colors haha).

**Comment by brianfleming** [comment]
Thanks for the comments and reviewing this @dariusk and @caiosba I will start to make additional changes to remove some of the testing things and get it all buttoned up with some README love.

@sonoransun it was suggested by @caiosba to get some thoughts from you on if anything is necessary to do to get this ready for a prod environment. Let me know if you would like to chat about it

**Comment by dariusk** [comment]
@brianfleming Okay, I tried implementing the new `TextField` using this system and it seems to be working! Implementation here:

https://github.com/meedan/check-web/commit/995da6894342b15bbcdb95b2c2ce2dcf59079767#diff-493778a701b83a2cc725516e78427208c4b1592d7836d181a2d4899cbf4117e6

We still have to work out fonts so right now I am (mostly) leaning on `Typography`, though you'll see here that for `placeholder` styling I had to manually specify the font stuff for now (there is no way to apply `Typography` to a placeholder in `material-ui`):

https://github.com/meedan/check-web/commit/995da6894342b15bbcdb95b2c2ce2dcf59079767#diff-a57b311a6c251dabc5c9d1e72f5e880f5fe706cafbe82cb4b254d857a144f3f0R29-R33

There is one place I had to use `!important` which seems like a code smell but I wasn't sure of another way around it:

https://github.com/meedan/check-web/commit/995da6894342b15bbcdb95b2c2ce2dcf59079767#diff-a57b311a6c251dabc5c9d1e72f5e880f5fe706cafbe82cb4b254d857a144f3f0R105-R111

Anyway, overall this is really really good. It makes the code for `TextField` itself completely about the functionality and turns it from a 200 line thing into a 100 line thing by removing all the CSS!

**Comment by dariusk** [comment]
Oh yeah the other thing is I had a unit test that checked for the presence of a CSS class when you gave the component a `variant`. But when unit testing, there are no styles imported, it's all `undefined`. I guess I could figure out how to mock the styles, but I wasn't sure that it was a useful unit test in the first place so I removed it:

https://github.com/meedan/check-web/commit/995da6894342b15bbcdb95b2c2ce2dcf59079767#diff-1901fad92155381a1b7a026862071a0c0be131037d229064cf9c0d2128c2b05dL103-L145

**Comment by brianfleming** [comment]
> Oh yeah the other thing is I had a unit test that checked for the presence of a CSS class when you gave the component a `variant`. But when unit testing, there are no styles imported, it's all `undefined`. I guess I could figure out how to mock the styles, but I wasn't sure that it was a useful unit test in the first place so I removed it:
> 
> [995da68#diff-1901fad92155381a1b7a026862071a0c0be131037d229064cf9c0d2128c2b05dL103-L145](https://github.com/meedan/check-web/commit/995da6894342b15bbcdb95b2c2ce2dcf59079767#diff-1901fad92155381a1b7a026862071a0c0be131037d229064cf9c0d2128c2b05dL103-L145)

That is an interesting one. I don't think a blocker for this overall work, but definitely a subject that needs to further sussing out.

**Comment by brianfleming** [comment]
@sonoransun just wanted to ping you on this if you have any change requests as this PR is getting a bit long in the tooth and is blocking @dariusk [PR](https://github.com/meedan/check-web/pull/1404)

**Review by sonoransun — APPROVED** [review]
This looks good! Apologies for the delayed reply. The Travis and build.sh changes are all fine. Nothing of concern in package updates. The CSS changes don't interfere with the check-web config process for QA and Live. And I don't see any conflicts with the Uptime RUM check scripts. Good to go!

**Pull request merged**
