### PR TITLE
Fact-checks list

### PR DESCRIPTION
**Pull request by caiosba**
## Description

List of fact-checks.

Reference: CV2-4145.

## Type of change

- [ ] Performance improvement and/or refactoring (non-breaking change that keeps existing functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Security mitigation or enhancement
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Automated test (add or update automated tests)

## How has this been tested?

It relies on the tests of the articles component.

## Checklist

- [x] I have performed a self-review of my own code
- [x] I've made sure my branch is runnable and given good testing steps in the PR description
- [x] I considered secure coding practices when writing this code. Any security concerns are noted above.
- [x] I have commented my code in hard-to-understand areas, if any
- [ ] I have made needed changes to the README
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] If I implemented any new components, they are self-contained, their `propTypes` are declared and they use React Hooks and, if data-fetching is required, they use Relay Modern with fragment containers
- [ ] If my components involve user interaction - specifically button, text fields, or other inputs - I have added a [BEM-like class name](https://meedan.atlassian.net/wiki/spaces/ENG/pages/1327628289/Naming+conventions+for+interactive+elements) to the element that is interacted with
- [x] To the best of my knowledge, any new styles are applied according to the design system
- [ ] If I added a new external dependency, I included a rationale for doing so and an estimate of the change in bundle size (e.g., checked in https://bundlephobia.com/)

### CODE REVIEW

**Review by brianfleming — CHANGES_REQUESTED** [review]
sometimes I hate bringing up a petty little change by the designer, other times harassing a poor engineer on a friday is fun. Since this is @caiosba its the later!

Anyway @caiosba thanks for fixing the apply etc buttons showing up incorrectly, can you match the other list and do the same for the | ? see the screenshots below:


Screenshot 2024-05-31 at 12 35 43 PM

### versus

Screenshot 2024-05-31 at 12 35 49 PM

**Comment by caiosba** [comment]
> sometimes I hate bringing up a petty little change by the designer, other times harassing a poor engineer on a friday is fun. Since this is @caiosba its the later!
> 
> Anyway @caiosba thanks for fixing the apply etc buttons showing up incorrectly, can you match the other list and do the same for the | ? see the screenshots below:
> 
> 
> Screenshot 2024-05-31 at 12 35 43 PM
> 
> ### versus
> 
> Screenshot 2024-05-31 at 12 35 49 PM
> 
> 
> 

Hahaha will do!

**Comment by amoedoamorim** [comment]
Reviewing this now

**Review by amoedoamorim — APPROVED** [review]
:lgtm:

**Comment by caiosba** [comment]
> sometimes I hate bringing up a petty little change by the designer, other times harassing a poor engineer on a friday is fun. Since this is @caiosba its the later!
> 
> Anyway @caiosba thanks for fixing the apply etc buttons showing up incorrectly, can you match the other list and do the same for the | ? see the screenshots below:
> 
> Screenshot 2024-05-31 at 12 35 43 PM
> ### versus
> Screenshot 2024-05-31 at 12 35 49 PM

@brianfleming thanks, I pushed that fix!

**Pull request merged**
