### PR TITLE
typography classes for new css setup

### PR DESCRIPTION
**Pull request by brianfleming**
## Description

Continuation to work for [CV2-2878](https://meedan.atlassian.net/browse/CV2-2878) and to continue to step away from material design this PR:

- adds classes for our current typography variables that match figma
- start to remove old references to js type settings in `shared.js`
- random replacements of `shared.js` colors for color vars

References: [CV2-2878](https://meedan.atlassian.net/browse/CV2-2878)

## Type of change

- [x] Performance improvement and/or refactoring (non-breaking change that keeps existing functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Automated test (add or update automated tests)

## How has this been tested?

Manual testing

## Things to pay attention to during code review

Please describe parts of the change that require extra attention during code review, for example:

- File FFFF, line LL: This refactoring does this and this. Is it consistent with how it’s implemented elsewhere?
- Etc.

## Checklist

- [x] I have performed a self-review of my own code
- [ ] I have commented my code in hard-to-understand areas, if any
- [ ] I have made needed changes to the README
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I implemented any new components, they are self-contained, their `propTypes` are declared and they use React Hooks and, if data-fetching is required, they use Relay Modern with fragment containers
- [ ] I have removed the /* eslint-disable @calm/react-intl/missing-attribute */ from any files I've worked on and added a `description` prop to all `<FormattedMessage />` components that were missing it.
- [ ] To the best of my knowledge, any new styles are applied according to the design system
- [ ] If I added a new external dependency, I included a rationale for doing so and an estimate of the change in bundle size (e.g., checked in https://bundlephobia.com/)

[CV2-2878]: https://meedan.atlassian.net/browse/CV2-2878?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CV2-2878]: https://meedan.atlassian.net/browse/CV2-2878?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by brianfleming** [comment]
@dariusk @amoedoamorim @danielevalverde wanted to get your eyes on this to see if you think this is a good direction.
I was talking with @dariusk about the new postcss stuff and his work on the textfield and we were talking about typography and how to handle it going forward an eventually getting us closer to removing material ui. So here are some thoughts around this PR

### This first step for now:
- I have added classes for each of our type settings into the globally scoped css, so they can be applied via a var in places where it makes sense, you can see that in this PR
- Continue to use the current `<Typography...` in cases where its easier right now

### Possible future:
- maybe we just create our own 1:1 replacement custom `<Typography...` as a less "dangerous" swap out for material , so we just update the import statements?

**Comment by dariusk** [comment]
Just tested this with my new `TextField` component and it works great.

**Comment by brianfleming** [comment]
> Just tested this with my new `TextField` component and it works great.

nice @dariusk !!
If you are happy with this approach I can squash

**Review by dariusk — APPROVED** [review]
Looks great, squash and merge!

**Pull request merged**
