### PR TITLE
Article review updates

### PR DESCRIPTION
**Pull request by brianfleming**
## Description

- Move the article publication status to top of card. I meant to do this in my previous PR but forgot
- Remove restrictions to tagging a media cluster, leaving only the permissions restriction

References: CV2-5000

## Type of change

- [x] Performance improvement and/or refactoring (non-breaking change that keeps existing functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Security mitigation or enhancement
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Automated test (add or update automated tests)

## How has this been tested?

manual testing

## Things to pay attention to during code review

- will add a PR comment about one this to note

## Checklist

- [x] I have performed a self-review of my own code
- [ ] I've made sure my branch is runnable and given good testing steps in the PR description
- [ ] I considered secure coding practices when writing this code. Any security concerns are noted above.
- [ ] I have commented my code in hard-to-understand areas, if any
- [ ] I have made needed changes to the README
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I implemented any new components, they are self-contained, their `propTypes` are declared and they use React Hooks and, if data-fetching is required, they use Relay Modern with fragment containers
- [ ] If my components involve user interaction - specifically button, text fields, or other inputs - I have added a [BEM-like class name](https://meedan.atlassian.net/wiki/spaces/ENG/pages/1327628289/Naming+conventions+for+interactive+elements) to the element that is interacted with
- [x] To the best of my knowledge, any new styles are applied according to the design system
- [ ] If I added a new external dependency, I included a rationale for doing so and an estimate of the change in bundle size (e.g., checked in https://bundlephobia.com/)

### CODE REVIEW

**Comment by brianfleming** [comment]
@caiosba this PR removes those restrictions on tagging.
let me know if this is a problem, but now the tagging throws that `Uncaught TypeError: "style" is read-only` and the tag doesn't show up until refresh. So not sure if this is just a local thing and will be fine in prod mode, but wanted to highlight it

**Comment by caiosba** [comment]
> @caiosba this PR removes those restrictions on tagging. let me know if this is a problem, but now the tagging throws that `Uncaught TypeError: "style" is read-only` and the tag doesn't show up until refresh. So not sure if this is just a local thing and will be fine in prod mode, but wanted to highlight it

Thanks, this sounds like the issues we have with Relay updates locally. Let me try now (at the same time that I review the PR). BTW, you may be able to run in "production" mode too (I didn't test on Mac), as per the second bullet point at https://github.com/meedan/check-web?tab=readme-ov-file#notes-and-tips (it's just a lot slower).

**Review by caiosba — APPROVED** [review]
Code looks good and works as expected locally (even auto-refresh)!

**Comment by caiosba** [comment]
> > @caiosba this PR removes those restrictions on tagging. let me know if this is a problem, but now the tagging throws that `Uncaught TypeError: "style" is read-only` and the tag doesn't show up until refresh. So not sure if this is just a local thing and will be fine in prod mode, but wanted to highlight it
> 
> Thanks, this sounds like the issues we have with Relay updates locally. Let me try now (at the same time that I review the PR). BTW, you may be able to run in "production" mode too (I didn't test on Mac), as per the second bullet point at https://github.com/meedan/check-web?tab=readme-ov-file#notes-and-tips (it's just a lot slower).

Confirmed. Works well locally running in production mode.

**Pull request merged**
