### PR TITLE
Feature flag for data dashboard

### PR DESCRIPTION
**Pull request by caiosba**
## Description

- Articles Dashboard: Display the “Dashboard” option on the sidebar only for super-admins.
- Tipline Dashboard: The option will be displayed and accessible by all users, but then, on the page, the charts are only displayed for super-admins - other users only see the table.

Reference: CV2-5401.

## Type of change

- [ ] Performance improvement and/or refactoring (non-breaking change that keeps existing functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Security mitigation or enhancement
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Automated test (add or update automated tests)

## How has this been tested?

See description above.

## Checklist

- [x] I have performed a self-review of my own code
- [x] I've made sure my branch is runnable and given good testing steps in the PR description
- [x] I considered secure coding practices when writing this code. Any security concerns are noted above.
- [ ] I have commented my code in hard-to-understand areas, if any
- [ ] I have made needed changes to the README
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I implemented any new components, they are self-contained, their `propTypes` are declared and they use React Hooks and, if data-fetching is required, they use Relay Modern with fragment containers
- [ ] If my components involve user interaction - specifically button, text fields, or other inputs - I have added a [BEM-like class name](https://meedan.atlassian.net/wiki/spaces/ENG/pages/1327628289/Naming+conventions+for+interactive+elements) to the element that is interacted with
- [ ] To the best of my knowledge, any new styles are applied according to the design system
- [ ] If I added a new external dependency, I included a rationale for doing so and an estimate of the change in bundle size (e.g., checked in https://bundlephobia.com/)
- [ ] If I touched a file that included an eslint-disable-file header, I updated the code such that the disabler can be removed

### CODE REVIEW

**Review by danielevalverde — CHANGES_REQUESTED** [review]
Hi, @caiosba :) 

I noticed something here:
As a non-admin user, when navigating to the Tipline dashboard page, the line that separates the chat from the data table is still visible, and I believe it shouldn't be shown in this case.

Captura de tela_2024-11-07_09-43-38

**Comment by caiosba** [comment]
> Hi, @caiosba :)
> 
> I noticed something here: As a non-admin user, when navigating to the Tipline dashboard page, the line that separates the chat from the data table is still visible, and I believe it shouldn't be shown in this case.
> 
> Captura de tela_2024-11-07_09-43-38

Good catch, Dani! Will fix.

**Comment by caiosba** [comment]
Fixed, @danielevalverde - please re-review.

**Comment by danielevalverde** [comment]
> Fixed, @danielevalverde - please re-review.

@caiosba, I think we need to update the EPIC branch, as this PR currently shows file changes related to Chinel's recent updates. Refreshing the branch should help ensure that only the intended changes for this PR are displayed :)

**Comment by caiosba** [comment]
Ah, yes, I was targeting @amoedoamorim's branch, but he merged it already - I changed it to `develop` now, @danielevalverde

**Review by danielevalverde — APPROVED** [review]
Code and funciotionality :LGTM:

**Pull request merged**
