### PR TITLE
Feed title updates

### PR DESCRIPTION
**Pull request by brianfleming**
## Description

Updates to the shared feed title when the title is very long as reported in  [CV2-2830](https://meedan.atlassian.net/browse/CV2-2830)

I also added a limit to the feed list title for now. will re-address this when there are multiple orgs in the feed

References: [CV2-2830](https://meedan.atlassian.net/browse/CV2-2830)

## Type of change

- [ ] Performance improvement and/or refactoring (non-breaking change that keeps existing functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Automated test (add or update automated tests)

## How has this been tested?

manual testing

### Long title with spaces 
Screenshot 2023-06-30 at 2 08 08 PM

### Long title NO spaces
Screenshot 2023-06-30 at 2 08 49 PM

### Short title
Screenshot 2023-06-30 at 2 08 40 PM

### Feed list title
Screenshot 2023-06-30 at 2 21 25 PM

## Checklist

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code in hard-to-understand areas, if any
- [ ] I have made needed changes to the README
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I implemented any new components, they are self-contained, their `propTypes` are declared and they use React Hooks and, if data-fetching is required, they use Relay Modern with fragment containers
- [ ] I have removed the /* eslint-disable @calm/react-intl/missing-attribute */ from any files I've worked on and added a `description` prop to all `<FormattedMessage />` components that were missing it.
- [ ] To the best of my knowledge, any new styles are applied according to the design system
- [ ] If I added a new external dependency, I included a rationale for doing so and an estimate of the change in bundle size (e.g., checked in https://bundlephobia.com/)

[CV2-2830]: https://meedan.atlassian.net/browse/CV2-2830?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CV2-2830]: https://meedan.atlassian.net/browse/CV2-2830?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by dariusk — APPROVED** [review]
Looks good!

**Comment by brianfleming** [comment]
I don't understand this failure. I just changed it from being a mat icon to a custom icon. they both output an svg, which is what the test is is looking for. Any ideas @dariusk @caiosba ?

`let feedTopBar = feedTopBarComponent.find('svg');`

**Comment by dariusk** [comment]
The issue here is that the way Jest is set up for us, it is rendering custom icons as `<SvgrURL />` rather than `<svg />`. I've pushed a commit that should fix this, and our unit tests all seem to be passing after the change.

**Comment by brianfleming** [comment]
> The issue here is that the way Jest is set up for us, it is rendering custom icons as `<SvgrURL />` rather than `<svg />`. I've pushed a commit that should fix this, and our unit tests all seem to be passing after the change.

Thanks @dariusk ! much appreciated

**Pull request merged**
