### PR TITLE
Feature/CV2-4697: show channels in item card

### PR DESCRIPTION
**Pull request by danielevalverde**
## Description

-  request the field channel in the GraphQL query and pass it to the cards so the channels can be listed correctly
- extract the channel PropType to the [shared propTypes file](https://github.com/meedan/check-web/blob/develop/src/app/CheckPropTypes.js)
- Add unit tests to cover the different formats of the channel field

Reference: CV2-4697

## Type of change

- [ ] Performance improvement and/or refactoring (non-breaking change that keeps existing functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Security mitigation or enhancement
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Automated test (add or update automated tests)

## How has this been tested?
- Add new unit tests

## Checklist

- [X] I have performed a self-review of my own code
- [ ] I've made sure my branch is runnable and given good testing steps in the PR description
- [ ] I considered secure coding practices when writing this code. Any security concerns are noted above.
- [ ] I have commented my code in hard-to-understand areas, if any
- [ ] I have made needed changes to the README
- [ ] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [ ] If I implemented any new components, they are self-contained, their `propTypes` are declared and they use React Hooks and, if data-fetching is required, they use Relay Modern with fragment containers
- [ ] If my components involve user interaction - specifically button, text fields, or other inputs - I have added a [BEM-like class name](https://meedan.atlassian.net/wiki/spaces/ENG/pages/1327628289/Naming+conventions+for+interactive+elements) to the element that is interacted with
- [ ] To the best of my knowledge, any new styles are applied according to the design system
- [ ] If I added a new external dependency, I included a rationale for doing so and an estimate of the change in bundle size (e.g., checked in https://bundlephobia.com/)

### CODE REVIEW

**Review by brianfleming — COMMENTED** [review]
Two things on this @danielevalverde 
1. Is there something I need to do to get the channels to show? I am on this API branch: https://github.com/meedan/check-api/pull/1924 is that correct? Currently nothing shows up in the list
2. we should not show the last bullet in the cards if there are no requests

See this screenshot for both things ^^

Screenshot 2024-06-18 at 4 28 40 PM

**Comment by danielevalverde** [comment]
> Two things on this @danielevalverde
> 
> 1. Is there something I need to do to get the channels to show? I am on this API branch: [Epic/cv2-3939: replace table view with cards check-api#1924](https://github.com/meedan/check-api/pull/1924) is that correct? Currently nothing shows up in the list
> 2. we should not show the last bullet in the cards if there are no requests
> 
> See this screenshot for both things ^^
> 
> Screenshot 2024-06-18 at 4 28 40 PM

@brianfleming ,   for the lists where items are created manually, you can mock the display of channels locally by modifying the CheckChannels configuration file.: https://github.com/meedan/check-web/blob/feature/CV2-4697-show-channels-in-item-card/src/app/CheckChannels.js#L8-L15
To test the channels are displayed correctly, you can change one of the channel tipline identifiers to 0, which is the identifier for manual items. For example, to display the WhatsApp icon, change the value for WHATSAPP from 5 to 0 

- Will address the second bullet

**Comment by brianfleming** [comment]
> > Two things on this @danielevalverde
> > 
> > 1. Is there something I need to do to get the channels to show? I am on this API branch: [Epic/cv2-3939: replace table view with cards check-api#1924](https://github.com/meedan/check-api/pull/1924) is that correct? Currently nothing shows up in the list
> > 2. we should not show the last bullet in the cards if there are no requests
> > 
> > See this screenshot for both things ^^
> > Screenshot 2024-06-18 at 4 28 40 PM
> 
> @brianfleming , for the lists where items are created manually, you can mock the display of channels locally by modifying the CheckChannels configuration file.: https://github.com/meedan/check-web/blob/feature/CV2-4697-show-channels-in-item-card/src/app/CheckChannels.js#L8-L15 To test the channels are displayed correctly, you can change one of the channel tipline identifiers to 0, which is the identifier for manual items. For example, to display the WhatsApp icon, change the value for WHATSAPP from 5 to 0
> 
> * Will address the second bullet

In my screenshot the "erere" one was manually created, so I expect it not to have any request so no channels. But the other ones were created using the seed file, and they do have request. So for example. Here is the item page for the one  "Open-source logistical database" which shows a facebook icon on the item request page

Screenshot 2024-06-18 at 4 46 23 PM

So I guess my followup questions are:
1. is this expected?
2. can we do something so the seed file items correctly show the channels in the list when using the seed script? Or maybe I need to rerun it?

**Comment by danielevalverde** [comment]
> > > Two things on this @danielevalverde
> > > 
> > > 1. Is there something I need to do to get the channels to show? I am on this API branch: [Epic/cv2-3939: replace table view with cards check-api#1924](https://github.com/meedan/check-api/pull/1924) is that correct? Currently nothing shows up in the list
> > > 2. we should not show the last bullet in the cards if there are no requests
> > > 
> > > See this screenshot for both things ^^
> > > Screenshot 2024-06-18 at 4 28 40 PM
> > 
> > 
> > @brianfleming , for the lists where items are created manually, you can mock the display of channels locally by modifying the CheckChannels configuration file.: https://github.com/meedan/check-web/blob/feature/CV2-4697-show-channels-in-item-card/src/app/CheckChannels.js#L8-L15 To test the channels are displayed correctly, you can change one of the channel tipline identifiers to 0, which is the identifier for manual items. For example, to display the WhatsApp icon, change the value for WHATSAPP from 5 to 0
> > 
> > * Will address the second bullet
> 
> In my screenshot the "erere" one was manually created, so I expect it not to have any request so no channels. But the other ones were created using the seed file, and they do have request. So for example. Here is the item page for the one "Open-source logistical database" which shows a facebook icon on the item request page
> 
> Screenshot 2024-06-18 at 4 46 23 PM
> So I guess my followup questions are:
> 
> 1. is this expected?
> 2. can we do something so the seed file items correctly show the channels in the list when using the seed script? Or maybe I need to rerun it?

@brianfleming, I just updated the seed file and merged the PR(https://github.com/meedan/check-api/pull/1932)  to the epic branch, so please update the epic branch(https://github.com/meedan/check-api/pull/1924) and rerun the seed file, and let me know if there are any issues or if anything is still missing.

**Review by amoedoamorim — APPROVED** [review]

**Review by brianfleming — CHANGES_REQUESTED** [review]
Thanks for the seeds file update @danielevalverde ! worked.
So the only thing left is the trailing bullet when there are no requests. See the screenshot below. The first cards has zero request, but the last bullet separator is still there

Screenshot 2024-06-20 at 9 41 34 AM

**Comment by danielevalverde** [comment]
> Thanks for the seeds file update @danielevalverde ! worked. So the only thing left is the trailing bullet when there are no requests. See the screenshot below. The first cards has zero request, but the last bullet separator is still there
> 
> Screenshot 2024-06-20 at 9 41 34 AM

Thanks @brianfleming! sent the fix, Could you please re-test? :)

**Review by brianfleming — APPROVED** [review]
Nice! thanks for that change @danielevalverde 
The bullets are correctly there or not there!

bullet

**Pull request merged**
