### PR TITLE
Settings styles cleanup and consolidation CV2-3363

### PR DESCRIPTION
**Pull request by brianfleming**
## Description

This PR is the first pass at addressing CV2-3363, which is a wide spread ticket around consolidating styles in the settings area.
I am breaking these PRs up to limit the scope of changes, although this PR is admittedly unfortunately large.
This PR primarily focuses on the settings header and containers.
The styles of the containers are closer to the new containers introduced in the shared feeds area, this will be used going forward.
Future PRs will continue to clean up style drift in the settings area, and we will close the ticket when we are closer to consistency. 

- Remove references to the previously deprecated subtitle for settings header
- add stylesheets for settings areas
- update to cds components where appropriate
- add any missing localization description messages
- adds back the Tags count to the tags settings header

References: [CV2-3363](https://meedan.atlassian.net/browse/CV2-3363)

## Type of change

- [x] Performance improvement and/or refactoring (non-breaking change that keeps existing functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Automated test (add or update automated tests)

## How has this been tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can verify the changes. Please describe whether or not you implemented automated tests.

## Things to pay attention to during code review

During review we are looking for any code or styles are blatantly incorrect, or that would stop a deployment. It should be taken that this is just a step in the right direction and not meant to address everything. 

## Checklist

- [x] I have performed a self-review of my own code
- [x] I've made sure my branch is runnable and given good testing steps in the PR description
- [ ] I have commented my code in hard-to-understand areas, if any
- [ ] I have made needed changes to the README
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I implemented any new components, they are self-contained, their `propTypes` are declared and they use React Hooks and, if data-fetching is required, they use Relay Modern with fragment containers
- [ ] I have removed the /* eslint-disable @calm/react-intl/missing-attribute */ from any files I've worked on and added a `description` prop to all `<FormattedMessage />` components that were missing it.
- [x] To the best of my knowledge, any new styles are applied according to the design system
- [ ] If I added a new external dependency, I included a rationale for doing so and an estimate of the change in bundle size (e.g., checked in https://bundlephobia.com/)

[CV2-3363]: https://meedan.atlassian.net/browse/CV2-3363?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by brianfleming** [comment]
Not sure why the integration tests are failing. I'm struggling to see what change results in these errors since they seem to be related to searching. I might need a little assistance on that.

@dariusk this is the PR I mentioned the other day when we were talking about tags paging fwiw

**Comment by dariusk** [comment]
@brianfleming In my experience these exact 4 search related tests just fail from time to time. If you're not working on these components it's safe to ignore and consider the tests passing.

**Comment by brianfleming** [comment]
thanks @dariusk , not to brag, but I'm pretty good at ignoring tests 😸 
will revert the testing!

**Comment by amoedoamorim** [comment]
I'll go over this in small batches throughout the day!

**Comment by amoedoamorim** [comment]
I'll be back to this later today!

**Comment by brianfleming** [comment]
Hey @amoedoamorim just wanted to reach out with a friendly ping on this, see if you have any change requests. Thanks!

**Review by amoedoamorim — APPROVED** [review]
Phew! Sorry it took so long! :lgtm:

**Pull request merged**
