### PR TITLE
feed requests button

### PR DESCRIPTION
**Pull request by brianfleming**
## Description

Add the ability to move between regular shared feed list and INE style

References: [CV2-4376]

## Type of change

- [x] Performance improvement and/or refactoring (non-breaking change that keeps existing functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Security mitigation or enhancement
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Automated test (add or update automated tests)

### AFTER Toggle Button Group
Screenshot 2024-03-11 at 1 50 04 PM

## Checklist

- [x] I have performed a self-review of my own code
- [x] I've made sure my branch is runnable and given good testing steps in the PR description
- [x] I considered secure coding practices when writing this code. Any security concerns are noted above.
- [ ] I have commented my code in hard-to-understand areas, if any
- [ ] I have made needed changes to the README
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I implemented any new components, they are self-contained, their `propTypes` are declared and they use React Hooks and, if data-fetching is required, they use Relay Modern with fragment containers
- [ ] If my components involve user interaction - specifically button, text fields, or other inputs - I have added a [BEM-like class name](https://meedan.atlassian.net/wiki/spaces/ENG/pages/1327628289/Naming+conventions+for+interactive+elements) to the element that is interacted with
- [x] To the best of my knowledge, any new styles are applied according to the design system
- [ ] If I added a new external dependency, I included a rationale for doing so and an estimate of the change in bundle size (e.g., checked in https://bundlephobia.com/)

[CV2-4376]: https://meedan.atlassian.net/browse/CV2-4376?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by brianfleming** [comment]
ok @caiosba I think I didi this correctly, let me know if anything needs to change

**Comment by caiosba** [comment]
> ok @caiosba I think I didi this correctly, let me know if anything needs to change

Thank you, I'm going to review this later today!

**Review by caiosba — CHANGES_REQUESTED** [review]
Thanks @brianfleming, but I think there was a confusion here (correct me if I'm wrong please): since API requests can be received only when the feed is sharing published fact-checks (otherwise the API requests wouldn't return anything), the switcher should not be added to `FeedClusters` component (which is the component rendered when the feed is sharing media and requests), but to the `Feed` component, for the case when the feed is sharing fact-checks. Right? I pushed a commit that fixes it, and I also extracted the switcher as a separate component just to avoid code repetition and to make it easier for us when we hopefully delete all that code :stuck_out_tongue:

**Comment by caiosba** [comment]
So, it looks good to me after these changes, feel free to merge if it looks good to you too @brianfleming :)

**Review by caiosba — APPROVED** [review]

**Comment by brianfleming** [comment]
> Thanks @brianfleming, but I think there was a confusion here (correct me if I'm wrong please): since API requests can be received only when the feed is sharing published fact-checks (otherwise the API requests wouldn't return anything), the switcher should not be added to `FeedClusters` component (which is the component rendered when the feed is sharing media and requests), but to the `Feed` component, for the case when the feed is sharing fact-checks. Right? I pushed a commit that fixes it, and I also extracted the switcher as a separate component just to avoid code repetition and to make it easier for us when we hopefully delete all that code 😛

yeah you are right. I was hoping to have it outside of the filters, but really this should be deleted as you said, so lets just get past it. Thanks for your help clearing that up

**Pull request merged**
