### PR TITLE
Feature/webpack dev mode improvements

### PR DESCRIPTION
**Pull request by adamhooper**
* Nix Webpack HMR stuff that didn't work
* Prevent React Dev Tools error on page load (because previously it was running in production mode with a bundled dev mode)
* Enable source maps by default in dev mode ... without a speed hit!
* Set `watchOptions.ignored` so one doesn't need to modify kernel params to use Webpack watch mode.

### CODE REVIEW

**Comment by adamhooper** [comment]
@amoedoamorim I made a change that ought to fix the React Development Tools error you screenshotted yesterday. Could you please verify that it does?

Since there are changes to Webpack and `node_modules`, the best approach is to stop and restart `docker-compose` after checking this branch.

**Comment by infojunkie** [comment]
Just to make sure I understand: this does NOT mean that devs working on frontend will need to restart `docker-compose` at each modification, right?

**Comment by adamhooper** [comment]
@infojunkie Right, I'm just talking about this one time, to test this pull request, because the Webpack config has changed in this pull request.

(btw: We've determined my pull request doesn't solve the main problem, so I need to plug away at it.)

**Comment by adamhooper** [comment]
@caiosba @amoedoamorim Could you please review this set of changes? I feel this should all be merged into `develop`.

Change summary:

* `check-web/Dockerfile`: nix `npm install` ([Mantis issue 8089](https://mantis.meedan.com/view.php?id=8089))
* `react-jsonschema-form-material-ui`: use a Meedan-owned fork, `adamhooper/react-jsonschema-form-material-ui`, published as `meedan-check-react-jsonschema-form-material-ui-v1`, which I'm working to move over to the npmjs `meedan` org. (issue 8089) This fixes the React Developer Tools error message about having production+development versions of React.
* Absorb `react-video-js-player` and adapt it to our code style. This, too, prevents bundling a second version of React.
* Upgrade to Babel 7.
* Upgrade React Relay to 1.7.0. (Part of [Mantis issue 6211](https://mantis.meedan.com/view.php?id=6211)) This fixes many console warnings about `componentWillReceiveProps()` ([Mantis issue 8090](https://mantis.meedan.com/view.php?id=8090)); it also means new, forward-compatible Babel machinery.
* Nix server-side Babel. Use regular NodeJS 12 now.
* Move everything from `.babelrc` into Webpack config.
* Update Webpack config (which is still Webpack 2, for now) to be more Webpack 4-like: always emit source maps; don't minify in dev mode.
* New `babel-plugin-react-intl` config: 
* Nix a metric ton of dependencies (-63 +26 direct production-mode deps; -481 +310 deps in package-lock.json); patch-upgrade many deps; and dedupe a few as well.

Now, this one last time, to keep the Docker-volume node_modules in sync with `package-lock.json`, be sure to follow all these steps:

1. `docker-compose down --remove-orphans`
2. `docker-compose build`
3. `docker volume rm check_web-node_modules`
4. `docker-compose up web`

In the future, `docker-compose up web` will run `npm install`, which will resynchronize your node_modules. Also, always edit `package-lock.json` using `npm install` and `npm remove`, to maintain synchronicity.

**Pull request merged**
