### PR TITLE
Fix/cv2 5735 apply admin filter to all thumbnails

### PR DESCRIPTION
**Pull request by sarahkeh**
## Description

The admin content filter now puts a value to local storage.  This lets items not in the component tree pull from the same value.  Added a check in the ItemThumbnail component that looks for this flag and uses that to also determine if content should be hidden.  Also added a prop to ItemThumbnail that by default ignores this new localstorage value, to avoid impacts to other pages in the application.  For the item main icon and the search results in the Merge items, that value is set to false, allowing the thumbnail to be hidden by the admin flag.  

References: CV2-5735

## Type of change

- [ ] Performance improvement and/or refactoring (non-breaking change that keeps existing functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Security mitigation or enhancement
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Automated test (add or update automated tests)

## How has this been tested?

Manually

## Things to pay attention to during code review

Please describe parts of the change that require extra attention during code review, for example:

- File FFFF, line LL: This refactoring does this and this. Is it consistent with how it’s implemented elsewhere?
- Etc.

## Checklist

- [x] I have performed a self-review of my own code
- [x] I've made sure my branch is runnable and given good testing steps in the PR description
- [x] I considered secure coding practices when writing this code. Any security concerns are noted above.
- [x] I have commented my code in hard-to-understand areas, if any
- [ ] I have made needed changes to the README
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I implemented any new components, they are self-contained, their `propTypes` are declared and they use React Hooks and, if data-fetching is required, they use Relay Modern with fragment containers
- [ ] If my components involve user interaction - specifically button, text fields, or other inputs - I have added a [BEM-like class name](https://meedan.atlassian.net/wiki/spaces/ENG/pages/1327628289/Naming+conventions+for+interactive+elements) to the element that is interacted with
- [ ] To the best of my knowledge, any new styles are applied according to the design system
- [ ] If I added a new external dependency, I included a rationale for doing so and an estimate of the change in bundle size (e.g., checked in https://bundlephobia.com/)
- [ ] If I touched a file that included an eslint-disable-file header, I updated the code such that the disabler can be removed

### CODE REVIEW

**Review by brianfleming — COMMENTED** [review]
@sarahkeh a bit hard to explain, and also not sure if what I am seeing is part of this work, but its at the very least thematically aligned:

There is some sort of bug/deoptimization around the thumbnail in the header and using the admin protections and using the content warning. It can get in a state where the header thumbnail doesn't always "respect" the user action. Take a look at the screen recording and see if this helps, as I said, tough to explain:

https://github.com/user-attachments/assets/114c19ec-50a9-46f7-889d-2283fb623a16

let me know if i can provide anymore info or what your thoughts are if this is aligned. It also might be something to solve "later" in the next steps of the epic work 🤷

**Comment by sarahkeh** [comment]
@brianfleming I think this might be a separate issue.... I played around in QA and setting the content warning updates the thumbnail because it's a data update, but when it's temporarily lifted, that's just a temporary front end tag and, like how the Admin filter used to be, it's in a different component tree.  So it's similar, but unlike the admin/general content filter in the epic, it's very item-specific.... Personally it makes sense that the "Temporarily view content" only shows the large preview, since that's where the button is.  But maybe adding a "peek" button or something on the thumbnails might be helpful?

**Comment by brianfleming** [comment]
> @brianfleming I think this might be a separate issue.... I played around in QA and setting the content warning updates the thumbnail because it's a data update, but when it's temporarily lifted, that's just a temporary front end tag and, like how the Admin filter used to be, it's in a different component tree. So it's similar, but unlike the admin/general content filter in the epic, it's very item-specific.... Personally it makes sense that the "Temporarily view content" only shows the large preview, since that's where the button is. But maybe adding a "peek" button or something on the thumbnails might be helpful?

I think some of that makes sense @sarahkeh but there is something that I unfortunately didn't show in the video, but here is a video a followup question:

why is it that the header thumbnail is the only one that sometimes I can't get to uncover. take a look at this vid, all all the media responding to my actions except the main one:

https://github.com/user-attachments/assets/7b940fb8-0d81-40ea-826a-6e6764853752

**Comment by amoedoamorim** [comment]
@brianfleming I had a 1:1 with Sarah today and I see there are some problems with this functionality architecture.

As you know these two forms of hiding content are working independently, the per item content flag is data-driven and the admin screen is a frontend-only state.

The problem evidenced in the first video is because the components are under different Relay containers, unfortunately.
Because of how the code evolverd over time, `ItemThumbnail` in under a Relay classic container at `MediaActionsBar` and the `MediaCardLarge` is under a Relay modern QueryRenderer in `Media.js`. For this reason when you add content flag to an item, the large preview is hidden immediately but the thumbnail isn't aware of the change. But if you reload the page both get the updated data with the content flag set and will be hidden.
 
And the problem you evidence in the second video is probably because both flags function independently and the view temporarily toggle is local to `AspectRatio` which in effect applies the content cover. It seem that the item content flag is active, but the larger preview had the `Temporarily view content` on but that doesn't propagate to the item thumbnail. But you were clicking the Pause/resume admin screen button that also wouldn't affect the item content flag.

I think some refactoring there so the whole item page has a single QueryRenderer would make sense as we need to get rid of the Relay Classic stuff and would simplify things a great deal. We should also flatten `MediaPage`, `MediaPageLayout`, `Media` and maybe even `MediaComponent`. Too many layers there unnecessarily, imo.

So another benefit of a refactoring here is to lift that temporary view state management to the common ancestor  `MediaComponent` which would propagate the item content flag data to all its children.

I'd love to chat and structure a coherent architecture that can stand future iterations rather than just patching this already bad scenario.

**Comment by brianfleming** [comment]
> @brianfleming I had a 1:1 with Sarah today and I see there are some problems with this functionality architecture.
> 
> As you know these two forms of hiding content are working independently, the per item content flag is data-driven and the admin screen is a frontend-only state.
> 
> The problem evidenced in the first video is because the components are under different Relay containers, unfortunately. Because of how the code evolverd over time, `ItemThumbnail` in under a Relay classic container at `MediaActionsBar` and the `MediaCardLarge` is under a Relay modern QueryRenderer in `Media.js`. For this reason when you add content flag to an item, the large preview is hidden immediately but the thumbnail isn't aware of the change. But if you reload the page both get the updated data with the content flag set and will be hidden.
> 
> And the problem you evidence in the second video is probably because both flags function independently and the view temporarily toggle is local to `AspectRatio` which in effect applies the content cover. It seem that the item content flag is active, but the larger preview had the `Temporarily view content` on but that doesn't propagate to the item thumbnail. But you were clicking the Pause/resume admin screen button that also wouldn't affect the item content flag.
> 
> I think some refactoring there so the whole item page has a single QueryRenderer would make sense as we need to get rid of the Relay Classic stuff and would simplify things a great deal. We should also flatten `MediaPage`, `MediaPageLayout`, `Media` and maybe even `MediaComponent`. Too many layers there unnecessarily, imo.
> 
> So another benefit of a refactoring here is to lift that temporary view state management to the common ancestor `MediaComponent` which would propagate the item content flag data to all its children.
> 
> I'd love to chat and structure a coherent architecture that can stand future iterations rather than just patching this already bad scenario.

@amoedoamorim and @sarahkeh got it!
thanks for the comprehensive look into all of this. I agree with the conclusions that we need a larger refactor and I am not surprised its a Relay issue!

Since a lot of this is pre-existing and we are only really "seeing" some of these edge cases because of improvements @sarahkeh is making. I say we just keep moving forward with whatever path you both think is best, knowing that we are moving in the right direction. 

We can chat about the bigger refactor for a coherent architecture whenever makes sense, I think we are getting to a view of Check that we can be confident in a good choice for that refactor.

**Comment by amoedoamorim** [comment]
Hi @sarahkeh ! Code looks good, but I'm failing to understand why we need the new `ignoreGeneralContentMask` prop. Isn't the mask supposed to be applied everywhere, when active?

**Comment by sarahkeh** [comment]
@amoedoamorim Eventually, yes, but for right now it's still contained just in the Media Item page.  The change that moves the content filter to the List view is a later ticket

**Review by amoedoamorim — APPROVED** [review]

**Pull request merged**
