### PR TITLE
Revert "Bump @sentry/browser and @sentry/react"

### PR DESCRIPTION
**Pull request by amoedoamorim**
Reverts meedan/check-web#2147

### CODE REVIEW

**Comment by caiosba** [comment]
> Reverting this as it failed to build

CI didn't catch the build failure, @amoedoamorim ?

**Comment by amoedoamorim** [comment]
> > Reverting this as it failed to build
> 
> CI didn't catch the build failure, @amoedoamorim ?

I'm confused. Did I fail to notice it and merged by mistake?
It looks as it has passed, afaict:

image

**Comment by caiosba** [comment]
Yeah, looks like it passed. Since we're moving the Check Web CI to GitHub Actions, we don't need to fix it on Travis at this time, but something to keep an eye on.

**Comment by amoedoamorim** [comment]
image

https://github.com/meedan/check-web/pull/2147

**Review by caiosba — APPROVED** [review]

**Pull request merged**
