### PR TITLE
Added warning for users trying to search beyond 10000 items

### PR DESCRIPTION
**Pull request by sarahkeh**
## Description

Added an Alert message for users that try to navigate beyond 10k items, telling them to add additional filters.  Elastic Search is capped at 10k results so this is a simple fix if users encounter that.  

(mistakenly also included earlier work, remaking pull request with just the relevant changes for this bug fix)

## Type of change

- [ ] Performance improvement and/or refactoring (non-breaking change that keeps existing functionality)
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Security mitigation or enhancement
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Automated test (add or update automated tests)

## How has this been tested?

Tested with a cap of 100 results, was prompted with the Alert and couldn't click beyond that.  Increased cap to 10k, same results. 

## Things to pay attention to during code review

Please describe parts of the change that require extra attention during code review, for example:

If testing, reduce the cap size to something like 100 or 150, otherwise you're in for a lot of clicking. 

## Checklist

- [x] I have performed a self-review of my own code
- [x] I've made sure my branch is runnable and given good testing steps in the PR description
- [x] I considered secure coding practices when writing this code. Any security concerns are noted above.
- [x] I have commented my code in hard-to-understand areas, if any
- [ ] I have made needed changes to the README
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I implemented any new components, they are self-contained, their `propTypes` are declared and they use React Hooks and, if data-fetching is required, they use Relay Modern with fragment containers
- [ ] If my components involve user interaction - specifically button, text fields, or other inputs - I have added a [BEM-like class name](https://meedan.atlassian.net/wiki/spaces/ENG/pages/1327628289/Naming+conventions+for+interactive+elements) to the element that is interacted with
- [x] To the best of my knowledge, any new styles are applied according to the design system
- [ ] If I added a new external dependency, I included a rationale for doing so and an estimate of the change in bundle size (e.g., checked in https://bundlephobia.com/)

### CODE REVIEW

**Review by caiosba — APPROVED** [review]
Thanks @sarahkeh ! Code looks good and it works well for me locally (I used 100 as the limit):

Captura de tela de 2024-03-21 12-44-59

**Comment by sarahkeh** [comment]
@brianfleming How do you feel about the wording?   "Query returned too many results. Please use the filters to narrow down your search."

**Comment by brianfleming** [comment]
> @brianfleming How do you feel about the wording? "Query returned too many results. Please use the filters to narrow down your search."

Hmmm, yeah I don't think its quite right, because its less about the query being "bad" and more about the list display.
What are your thoughts on this:

`Browsing this list is limited to the first {{# of pages}} pages. Use the filters above to refine this list.`

**Comment by sarahkeh** [comment]
@brianfleming Can I use "10000 results" instead of number of pages? There aren't page numbers, just a range of items.

**Comment by brianfleming** [comment]
> @brianfleming Can I use "10000 results" instead of number of pages? There aren't page numbers, just a range of items.

sure! only request is to pass it through whatever formatter we have to make sure its `10,000` and not `10000`
If I wasn't super nit picky I would have to give back my designer card 😵‍💫

**Pull request merged**
