### PR TITLE
When choosing a fact-check to add to an item, search for all fact-checks, not only the ones that are not applied to any media cluster.

### PR DESCRIPTION
**Pull request by caiosba**
## Description

But the fact-checks that are already applied to a media cluster are not clickable. A tooltip is displayed with an explanation.

Fixes: CV2-5129.

## Type of change

- [ ] Performance improvement and/or refactoring (non-breaking change that keeps existing functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Security mitigation or enhancement
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Automated test (add or update automated tests)

## How has this been tested?

Manually.

## Things to pay attention to during code review

Captura de tela de 2024-08-27 00-07-40

## Checklist

- [x] I have performed a self-review of my own code
- [x] I've made sure my branch is runnable and given good testing steps in the PR description
- [x] I considered secure coding practices when writing this code. Any security concerns are noted above.
- [ ] I have commented my code in hard-to-understand areas, if any
- [ ] I have made needed changes to the README
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I implemented any new components, they are self-contained, their `propTypes` are declared and they use React Hooks and, if data-fetching is required, they use Relay Modern with fragment containers
- [ ] If my components involve user interaction - specifically button, text fields, or other inputs - I have added a [BEM-like class name](https://meedan.atlassian.net/wiki/spaces/ENG/pages/1327628289/Naming+conventions+for+interactive+elements) to the element that is interacted with
- [ ] To the best of my knowledge, any new styles are applied according to the design system
- [ ] If I added a new external dependency, I included a rationale for doing so and an estimate of the change in bundle size (e.g., checked in https://bundlephobia.com/)
- [ ] If I touched a file that included an eslint-disable-file header, I updated the code such that the disabler can be removed

### CODE REVIEW

**Comment by caiosba** [comment]
@brianfleming , feel free to push a copy change to this branch directly.

**Review by amoedoamorim — APPROVED** [review]
:lgtm: :shipit:

**Comment by brianfleming** [comment]
Thanks @caiosba will review right now and let you know about copy shortly

**Comment by brianfleming** [comment]
@caiosba I added some changes. If you are happy with them we can merge:
- updated copy a bit
- added a different icon on hover for unavailable articles
- changed the opacity so they appear dimmer

Screenshot 2024-08-27 at 10 25 52 AM
-----
Screenshot 2024-08-27 at 10 25 57 AM

**Comment by caiosba** [comment]
Looks great! Thanks, @brianfleming !

**Pull request merged**
