### PR TITLE
Feature/cv2 3297 collapse expande for cards component

### PR DESCRIPTION
**Pull request by danielevalverde**
## Description

- Added two new icons to collapse and expand actions
- Added the button with the icons that is displayed when hovering the feed card on the feed page
- When clicking to collapse, truncate the title to one line and the description to two lines (initial state)
- When clicked to expand, display the full title and description

Please take a look on the "How has this been tested" section

References: CV2-3297

## Type of change

- [ ] Performance improvement and/or refactoring (non-breaking change that keeps existing functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Automated test (add or update automated tests)

## How has this been tested?

- create a custom list
- create feed
- set this list to be "part of the shared feed" on feed settings
- add some items with long texts and long descriptions
#### Verify that:
 - on initial state/when the card is collapsed: the title is truncated to one line and the description to two lines
- When clicked to expand, display the full title and description
- when hovering the feed card on the feed page the button to "expand/collapse" the card is displayed

## Checklist

- [X] I have performed a self-review of my own code
- [X] I've made sure my branch is runnable and given good testing steps in the PR description
- [ ] I have commented my code in hard-to-understand areas, if any
- [ ] I have made needed changes to the README
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I implemented any new components, they are self-contained, their `propTypes` are declared and they use React Hooks and, if data-fetching is required, they use Relay Modern with fragment containers
- [ ] I have removed the /* eslint-disable @calm/react-intl/missing-attribute */ from any files I've worked on and added a `description` prop to all `<FormattedMessage />` components that were missing it.
- [ ] To the best of my knowledge, any new styles are applied according to the design system
- [ ] If I added a new external dependency, I included a rationale for doing so and an estimate of the change in bundle size (e.g., checked in https://bundlephobia.com/)

### CODE REVIEW

**Review by dariusk — APPROVED** [review]
Looks good! Glad to see use of custom components and SVG here.

**Review by brianfleming — CHANGES_REQUESTED** [review]
@danielevalverde looking great...couple things to help the UX and not frustrate our users:

- [x] can you remove the border on this button?
- [x] You should stop propagation on the click, because right now when you click the expand, it also triggers clicking the fact-check link, which opens a new tab, so its unexpected to the user
- [x] The expand/contract toggle should not show up unless the content overflows. Otherwise as you can see in the screenshot, if I clicked that, nothing would happen and it would be confusing:
Screenshot 2023-07-07 at 4 08 47 PM

**Comment by danielevalverde** [comment]
> * [X]  can you remove the border on this button?
> * [X]  You should stop propagation on the click, because right now when you click the expand, it also triggers clicking the fact-check link, which opens a new tab, so its unexpected to the user
> * [X]  The expand/contract toggle should not show up unless the content overflows. Otherwise as you can see in the screenshot, if I clicked that, nothing would happen and it would be confusing:

applied your requests, @brianfleming . 
But please let me know if still there's anything missing. 
And thanks for all the advice :)

**Review by brianfleming — CHANGES_REQUESTED** [review]
Thanks for the great changes @danielevalverde !! woot!

Last thing to take this over the top and be awesome is to add an event listener for browser resize. That way, if there is content that needs or does not need this new button after the browser window changes size the user gets the correct functionality

**Comment by danielevalverde** [comment]
> Thanks for the great changes @danielevalverde !! woot!
> 
> Last thing to take this over the top and be awesome is to add an event listener for browser resize. That way, if there is content that needs or does not need this new button after the browser window changes size the user gets the correct functionality

Thank you, @brianfleming  :)
Added the event listener for browser resizing. 
Please let me know if anything is still missing.

**Review by brianfleming — APPROVED** [review]
Thanks for all the great changes @danielevalverde 

applause

**Pull request merged**
