### PR TITLE
[CV2-3243] Proposal to add classnames package to help manage css classes

### PR DESCRIPTION
**Pull request by brianfleming**
## Description

Discussion/Proposal PR to add the npm package [classnames](https://github.com/JedWatson/classnames) which is widely accepted as an easier way to manage multiple and conditional css classnames.
This PR:
- adds the package references
- updates the textfield component as an example on how to handle:
  - applying a global css class
  - handling multiple css module references

References: [CV2-3243](https://meedan.atlassian.net/browse/CV2-3243)

## Type of change

- [x] Performance improvement and/or refactoring (non-breaking change that keeps existing functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Automated test (add or update automated tests)

## How has this been tested?

manual testing

## Things to pay attention to during code review

- Take a look at the associated ticket to see the incorrect out of some class names from the textfield component:  [CV2-3243](https://meedan.atlassian.net/browse/CV2-3243)
- Link to the [classnames repo](https://github.com/JedWatson/classnames)
- Some other [interesting examples of its usage](https://mtm.dev/multiple-classnames-css-modules-react)

## Checklist

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code in hard-to-understand areas, if any
- [ ] I have made needed changes to the README
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I implemented any new components, they are self-contained, their `propTypes` are declared and they use React Hooks and, if data-fetching is required, they use Relay Modern with fragment containers
- [ ] I have removed the /* eslint-disable @calm/react-intl/missing-attribute */ from any files I've worked on and added a `description` prop to all `<FormattedMessage />` components that were missing it.
- [ ] To the best of my knowledge, any new styles are applied according to the design system
- [ ] If I added a new external dependency, I included a rationale for doing so and an estimate of the change in bundle size (e.g., checked in https://bundlephobia.com/)

[CV2-3243]: https://meedan.atlassian.net/browse/CV2-3243?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CV2-3243]: https://meedan.atlassian.net/browse/CV2-3243?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by dariusk — COMMENTED** [review]
So this is an additional external dependency, though it's only 18kb bundled. Still, I'm wondering if it's worth it for what to me seems like syntactic sugar. Does it make our code more readable to have something in place that requires the reader to know how `cx` works (versus JS template strings and conditionals that everyone should baseline know)? Honest question there, I just don't know.

For reference, the existing code without `cx` in the PR looks like this:
```jsx
          className={`typography-body1 ${styles.input} ${disabled && styles.disabled} ${error && styles.error} ${variant === 'outlined' && styles.outlined} ${iconLeft && styles['input-icon-left']} ${iconRight && styles['input-icon-right']}`}
```

An example of this refactored with `cx` per the PR looks like this:

```jsx
          className={cx(
            'typography-body1',
            [styles.input],
            {
              [styles.disabled]: disabled,
              [styles.error]: error,
              [styles.outlined]: variant === 'outlined',
              [styles['input-icon-left']]: iconLeft,
              [styles['input-icon-right']]: iconRight,
            })
          }
```
While that's a definite improvement in readability, I wonder how it compares to just changing the whitespace on the original:

```jsx
          className={`
            typography-body1
            ${styles.input}
            ${disabled && styles.disabled}
            ${error && styles.error}
            ${variant === 'outlined' && styles.outlined}
            ${iconLeft && styles['input-icon-left']}
            ${iconRight && styles['input-icon-right']}`
          `}
```

Again, not sure what the right approach here is but I feel like introducing a third party package essentially to concatenate strings is overkill. Would love some feedback from @amoedoamorim, and @danielevalverde.

**Comment by brianfleming** [comment]
great comment @dariusk exactly why I put this up to see where it would land.
Just to add though, correct me if I'm wrong, but if we were to keep the existing code and wanted to "fix" the "bug" outline in [CV2-3243](https://meedan.atlassian.net/browse/CV2-3243) we would need to change the class application to like ternary or something in order to not out put `null` or `false` something like

### BEFORE
`...${disabled && styles.disabled}...`

### after
`...${disabled ? styles.disabled : ''}...`

correct?

**Comment by dariusk** [comment]
@brianfleming Correct! And good catch, yeah

**Comment by amoedoamorim** [comment]
I like it and I'm happy to use it! I think it helps prevent outputting unwanted `false`, `null` or `undefined` to classnames and also helps writing very readable conditional css.
I think the cost of learning how to work with it and the package size are neglectable.

**Comment by brianfleming** [comment]
I paired with @amoedoamorim on this before his review. Just wanted to circle back and land on a consensus if this should be merged. I added @danielevalverde as a reviewer to get more eyes/thoughts. @danielevalverde if you have any questions let me know.

**Review by danielevalverde — APPROVED** [review]
as I understand, this approach will help avoid the issue on the ticket "unintended css classnames being output", so happy to approve it :)

**Comment by brianfleming** [comment]
@dariusk since you expressed some concerns I didn't want to move forward unless you were ok with this, so just checking in with you first

**Review by dariusk — APPROVED** [review]
All the reasoning here makes sense, happy to move to this!

**Comment by brianfleming** [comment]
nice. thanks everyone for the reviews. Good thing is, this doesn't have to change how anyone codes, but if you want to, this can make things easier 🙌

**Pull request merged**
