### PR TITLE
Fixes CV2-3071 scrolling issue on shared feeds

### PR DESCRIPTION
**Pull request by brianfleming**
## Description

- There was a class necessary to be applied to shared feeds list to enable scrolling. This was applied to other lists, but shared feeds was missing
- reduced the number of css classes applied to one name to make it clearer what the dom is doing and make sure its the "same" applied to all search results areas
- also removes styled components from Home.js in favor of a modules css file to make it easier to track down the applied styles
- 
References: [CV2-3071](https://meedan.atlassian.net/browse/CV2-3071)

## Type of change

- [ ] Performance improvement and/or refactoring (non-breaking change that keeps existing functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Automated test (add or update automated tests)

## How has this been tested?

manual testing

### BEFORE (not incorrect vert scrollbar and no horizontal scrollbar)
Screenshot 2023-05-04 at 3 08 01 PM

### Shared feed AFTER (note scrollbars)
Screenshot 2023-05-04 at 2 56 29 PM

### Shared feed AFTER TSE MODEL (note scrollbars)
Screenshot 2023-05-04 at 2 57 40 PM

## Checklist

- [x] I have performed a self-review of my own code
- [x] I have commented my code in hard-to-understand areas, if any
- [ ] I have made needed changes to the README
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I implemented any new components, they are self-contained, their `propTypes` are declared and they use React Hooks and, if data-fetching is required, they use Relay Modern with fragment containers
- [ ] I have removed the /* eslint-disable @calm/react-intl/missing-attribute */ from any files I've worked on and added a `description` prop to all `<FormattedMessage />` components that were missing it.
- [x] To the best of my knowledge, any new styles are applied according to the design system
- [ ] If I added a new external dependency, I included a rationale for doing so and an estimate of the change in bundle size (e.g., checked in https://bundlephobia.com/)

[CV2-3071]: https://meedan.atlassian.net/browse/CV2-3071?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by dariusk — COMMENTED** [review]
I'm going to make a commit to this to run integration tests on the branch -- broad changes to class names like we are doing here can sometimes cause integration tests to fail due to a selector no longer work.

**Comment by dariusk** [comment]
Looks like we have some failing tests missing selectors -- I'll push a fix to the issue

**Comment by brianfleming** [comment]
> Looks like we have some failing tests missing selectors -- I'll push a fix to the issue

ahhh...i see why i missed these classes as part of tests. Thanks @dariusk

**Comment by dariusk** [comment]
Almost all cases have been fixed. Still seeing this:

```
  1) integration (chrome) web should set, edit and delete rules

     Failure/Error: raise "Could not find element with selector #{type.upcase} '#{selector}' after #{finish} seconds!" if elements.empty?   

     RuntimeError:

       Could not find element with selector CSS '#rules-table' after 62 seconds!
```

Did we move the rules table somewhere new? The `id` is still present in `team/Rules/RulesTable.js`

**Comment by brianfleming** [comment]
> rules-table

Not as part of this PR that I can see? it seems to be about the settings area correct?

**Comment by dariusk** [comment]
Yeah... I'm going to re-run the integration test. Might be a flake?

**Comment by dariusk** [comment]
It looks like these tests are failing due to a problem with search not working in the `test` environment and _probably_ nothing to do with your PR anymore. But let's see what happens when we get tests working again.

**Comment by brianfleming** [comment]
@caiosba @dariusk @danielevalverde considering the tests are a whole other thing, should i revert the integration tests on this branch?

**Comment by dariusk** [comment]
@brianfleming Yeah revert and then we can merge!

**Comment by brianfleming** [comment]
> @brianfleming Yeah revert and then we can merge!

done, thanks @dariusk

**Review by dariusk — APPROVED** [review]
Approving since the integration test failures are unrelated.

**Pull request merged**
