### PR TITLE
EPIC CV2-4441 - Articles

### PR DESCRIPTION
**Pull request by amoedoamorim**
## Description

This is the branch to consolidate all features from the CV2-4441 Articles EPIC.
Main changes for each ticket:

### API Epic PR:
[https://github.com/meedan/check-api/pull/1903](https://github.com/meedan/check-api/pull/1903)

### CV2-4501 (Daniele)

Add new rail item for Articles
Add tooltip to new rail item
Add new navigation item “Explainers” for articles

## Type of change

- [x] Very EPIC changes

### CV2-4501 (Daniele)

Please describe the tests that you ran to verify your changes. Provide instructions so we can verify the changes. Please describe whether or not you implemented automated tests.

### CV2-4501 (Daniele)

Please describe parts of the change that require extra attention during code review, for example:

- File FFFF, line LL: This refactoring does this and this. Is it consistent with how it’s implemented elsewhere?
- Etc.

### CODE REVIEW

**Comment by brianfleming** [comment]
@caiosba I noticed while reviewing the recent updates to this branch that the new explainers list, the filter bar when the page is first loaded incorrectly has the `Apply` and `Reset` buttons showing, so its behaving differently than other lists. Those should only show up when the filters have been changed by the user

Screenshot 2024-05-30 at 11 10 07 AM

**Comment by caiosba** [comment]
> @caiosba I noticed while reviewing the recent updates to this branch that the new explainers list, the filter bar when the page is first loaded incorrectly has the `Apply` and `Reset` buttons showing, so its behaving differently than other lists. Those should only show up when the filters have been changed by the user
> 
> Screenshot 2024-05-30 at 11 10 07 AM

I'll fix it!

**Comment by caiosba** [comment]
> @caiosba I noticed while reviewing the recent updates to this branch that the new explainers list, the filter bar when the page is first loaded incorrectly has the `Apply` and `Reset` buttons showing, so its behaving differently than other lists. Those should only show up when the filters have been changed by the user
> 
> Screenshot 2024-05-30 at 11 10 07 AM

@brianfleming , I fixed it in this commit in another branch (fact-checks list): https://github.com/meedan/check-web/pull/1958/commits/cdbf8eb74fe0d2469a90c5d8e386b8d417c9f5d3. Basically the issue is that the condition to hide the buttons should be one filter (since article type is always present), not zero. The fix is for the `<Articles />` component, so it will work for explainers and fact-checks.

**Comment by brianfleming** [comment]
Just wanted to flag here because I am not sure who is going to take this on, or if it fell between the cracks. but I noticed that the cards are not pulling in the tags. They show up if you add them during the article creation process, but not in the list itself and you can't add them via the list.
So just wanted to check to see if this is going to be done via the edit work @sarahkeh or is it part of another ticket @caiosba ?

**Comment by caiosba** [comment]
> Just wanted to flag here because I am not sure who is going to take this on, or if it fell between the cracks. but I noticed that the cards are not pulling in the tags. They show up if you add them during the article creation process, but not in the list itself and you can't add them via the list. So just wanted to check to see if this is going to be done via the edit work @sarahkeh or is it part of another ticket @caiosba ?

Hum, weird... I implemented setting tags for explainers and fact-checks from the cards... are you using the epic branch for the API side too, @brianfleming ?

**Comment by brianfleming** [comment]
> > Just wanted to flag here because I am not sure who is going to take this on, or if it fell between the cracks. but I noticed that the cards are not pulling in the tags. They show up if you add them during the article creation process, but not in the list itself and you can't add them via the list. So just wanted to check to see if this is going to be done via the edit work @sarahkeh or is it part of another ticket @caiosba ?
> 
> Hum, weird... I implemented setting tags for explainers and fact-checks from the cards... are you using the epic branch for the API side too, @brianfleming ?

yeah, just doubled checked and made sure I pulled latest on that branch. Does it work for you? i can show you on the front end call momentarily

**Comment by caiosba** [comment]
> > > Just wanted to flag here because I am not sure who is going to take this on, or if it fell between the cracks. but I noticed that the cards are not pulling in the tags. They show up if you add them during the article creation process, but not in the list itself and you can't add them via the list. So just wanted to check to see if this is going to be done via the edit work @sarahkeh or is it part of another ticket @caiosba ?
> > 
> > 
> > Hum, weird... I implemented setting tags for explainers and fact-checks from the cards... are you using the epic branch for the API side too, @brianfleming ?
> 
> yeah, just doubled checked and made sure I pulled latest on that branch. Does it work for you? i can show you on the front end call momentarily

Yeah, it works for me. OK, let's talk in the call.

**Review by caiosba — APPROVED** [review]
EPIC

**Pull request merged**
