### PR TITLE
Added Nepali translations

### PR DESCRIPTION
**Pull request by AshishMhrzn10**
I added Nepali language translations for Web.json.

### CODE REVIEW

**Comment by AshishMhrzn10** [comment]
@caiosba sir can I get a review??

**Comment by caiosba** [comment]
@amoedoamorim is on it :)

**Comment by AshishMhrzn10** [comment]
@amoedoamorim sir can I get a review??

**Comment by amoedoamorim** [comment]
@AshishMhrzn10 Thank you so much for your contribution! I'm a bit busy with other stuff right now but will review as soon as I can!

**Comment by amoedoamorim** [comment]
@AshishMhrzn10 By the way, are there strings all human translated?

**Comment by AshishMhrzn10** [comment]
okay brother.

**Comment by AshishMhrzn10** [comment]
yes i translated it not all but thanks to google, it helped a lot and I
updated much more to give sense .

**Pull request closed without merging**
