### PR TITLE
Deprecate some shared styles that are better done via css

### PR DESCRIPTION
**Pull request by brianfleming**
## Description

- There are styles in `shared.js` and `HeaderCard.js` that are either used in very few locations awaiting replacement by css files, or ready for deprecation. This PR keeps the process moving forward of moving to css files for styling
- `SpecialBlueCard` was deprecated in favor of the CDS Alert component. It was only used in 1 location
- Match invite pending styles on team members table in settings area
- Remove unused `HeaderCard.js`
- Remove unused `UserTooltip.js`

## Type of change

- [x] Performance improvement and/or refactoring (non-breaking change that keeps existing functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Security mitigation or enhancement
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Automated test (add or update automated tests)

## How has this been tested?

manual verification

### AFTER Create new item source
Screenshot 2024-01-12 at 11 07 34 AM

### AFTER User confirm email message
Screenshot 2024-01-11 at 4 55 35 PM

### AFTER message about needing to add email
Screenshot 2024-01-11 at 4 55 26 PM

### AFTER - Team members
Screenshot 2024-01-17 at 11 24 09 AM

## Checklist

- [x] I have performed a self-review of my own code
- [x] I've made sure my branch is runnable and given good testing steps in the PR description
- [x] I considered secure coding practices when writing this code. Any security concerns are noted above.
- [x] I have commented my code in hard-to-understand areas, if any
- [ ] I have made needed changes to the README
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I implemented any new components, they are self-contained, their `propTypes` are declared and they use React Hooks and, if data-fetching is required, they use Relay Modern with fragment containers
- [ ] If my components involve user interaction - specifically button, text fields, or other inputs - I have added a [BEM-like class name](https://meedan.atlassian.net/wiki/spaces/ENG/pages/1327628289/Naming+conventions+for+interactive+elements) to the element that is interacted with
- [x] To the best of my knowledge, any new styles are applied according to the design system
- [ ] If I added a new external dependency, I included a rationale for doing so and an estimate of the change in bundle size (e.g., checked in https://bundlephobia.com/)

### CODE REVIEW

**Comment by brianfleming** [comment]
Ok, integration test finally ran, thanks ngrok!
The 4 failures are our old friends it looks like. So open for review

**Review by caiosba — CHANGES_REQUESTED** [review]
@brianfleming, thanks, great stuff - code looks good, and based on the code changes, I reviewed the following features locally:

- [x] Upload file
- [ ] Search toolbar
- [x] User profile (each tab)
- [x] Workspace profile
- [x] Data dashboard
- [x] Confirm email screen

I just noticed one minor alignment issue with the search toolbar:

search-toolbar

**Comment by brianfleming** [comment]
Thanks for the review and catch @caiosba ! fixed up ready for another look

**Review by caiosba — APPROVED** [review]
LGTM!

**Pull request merged**
