### PR TITLE
Feature/3319 updated l10n procedures

### PR DESCRIPTION
**Pull request by amoedoamorim**
## Description

This commit makes Dockerfile install the new Transifex CLI client that supports their current API and includes translation files freshly downloaded with it and deprecates gulp tasks previously used a gulp-transifex npm package to connect with Transifex.

References: CV2-3319

## Type of change

- [ ] Performance improvement and/or refactoring (non-breaking change that keeps existing functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Automated test (add or update automated tests)

## How has this been tested?

Downloaded and Uploaded strings with new cli client from within the container, using the these commands that will be commited to the `update-l10n.sh` script in the parent repo:

```
echo 'Updating Check Web translations...' && \
(docker-compose exec web npm run transifex:merge-source) && \
(docker-compose exec web /tx push) && \
(docker-compose exec web /tx pull) && \
(docker-compose exec web npm run transifex:merge-translated)
```

# Things to pay attention to during code review

## Checklist

- [x] I have performed a self-review of my own code
- [x] I've made sure my branch is runnable and given good testing steps in the PR description
- [ ] I have commented my code in hard-to-understand areas, if any
- [ ] I have made needed changes to the README
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I implemented any new components, they are self-contained, their `propTypes` are declared and they use React Hooks and, if data-fetching is required, they use Relay Modern with fragment containers
- [ ] I have removed the /* eslint-disable @calm/react-intl/missing-attribute */ from any files I've worked on and added a `description` prop to all `<FormattedMessage />` components that were missing it.
- [ ] To the best of my knowledge, any new styles are applied according to the design system
- [ ] If I added a new external dependency, I included a rationale for doing so and an estimate of the change in bundle size (e.g., checked in https://bundlephobia.com/)

### CODE REVIEW

**Comment by dariusk** [comment]
@amoedoamorim Are you looking for a particular kind of review for this? I glanced at the code and it looks fine but I'm not sure if this is something I should try running locally or what.

**Comment by amoedoamorim** [comment]
@dariusk tbh I don't expect anyone to try it locally, at least not today. We can schedule a someone-else-trying-it for next Tuesday when it's the agreed day to update Transifex with new stuff, so we don't scare Localization Lab with new translations on a Friday!

**Comment by dariusk** [comment]
@amoedoamorim Okay, I sent you a calendar invite and we can save the official approval of the PR for then.

**Comment by amoedoamorim** [comment]
@dariusk sounds great! TY

**Review by dariusk — APPROVED** [review]
(We paired on a review for this, approved)

**Pull request merged**
