### PR TITLE
Remove Checkbox; Hide Published icon in shared feeds; Reuse ItemRepor…

### PR DESCRIPTION
**Pull request by amoedoamorim**
## Description

- Remove Checkbox; 
- Hide Published icon in shared feeds; 
- Reuse ItemReportStatus component

References: CV2-3939

## Type of change

- [ ] Performance improvement and/or refactoring (non-breaking change that keeps existing functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Security mitigation or enhancement
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Automated test (add or update automated tests)

## How has this been tested?

Manually viewing core/custom lists, fact-check/media feeds and ui-sandbox

## Things to pay attention to during code review

Please describe parts of the change that require extra attention during code review, for example:

- File FFFF, line LL: This refactoring does this and this. Is it consistent with how it’s implemented elsewhere?
- Etc.

## Checklist

- [x] I have performed a self-review of my own code
- [x] I've made sure my branch is runnable and given good testing steps in the PR description
- [ ] I considered secure coding practices when writing this code. Any security concerns are noted above.
- [ ] I have commented my code in hard-to-understand areas, if any
- [ ] I have made needed changes to the README
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I implemented any new components, they are self-contained, their `propTypes` are declared and they use React Hooks and, if data-fetching is required, they use Relay Modern with fragment containers
- [ ] If my components involve user interaction - specifically button, text fields, or other inputs - I have added a [BEM-like class name](https://meedan.atlassian.net/wiki/spaces/ENG/pages/1327628289/Naming+conventions+for+interactive+elements) to the element that is interacted with
- [ ] To the best of my knowledge, any new styles are applied according to the design system
- [ ] If I added a new external dependency, I included a rationale for doing so and an estimate of the change in bundle size (e.g., checked in https://bundlephobia.com/)

### CODE REVIEW

**Comment by amoedoamorim** [comment]
@brianfleming I have addressed these:

- Remove Checkbox; 
- Hide Published icon in shared feeds; 
- Reuse ItemReportStatus component;

Can you please review and see if it looks as expected?

**Review by brianfleming — CHANGES_REQUESTED** [review]
good progress @amoedoamorim only issue I see is:

- the cluster card is not getting the published date in the tooltip, but the article card is correctly showing

### Article card
Screenshot 2024-06-11 at 5 23 06 PM

### versus cluster card
Screenshot 2024-06-11 at 5 23 14 PM

**Comment by amoedoamorim** [comment]
@caiosba to address Brian's comment above what would be the correct piece of data and best way to get it?

My view is that ideally , since we have `item.report_status` we'd also want to have similarly `item.report_published_at` but there's no such field. I'm wondering if we should use `item.dynamic_annotation_report_design`'s `last_published` or something else?

**Comment by caiosba** [comment]
> @caiosba to address Brian's comment above what would be the correct piece of data and best way to get it?
> 
> My view is that ideally , since we have `item.report_status` we'd also want to have similarly `item.report_published_at` but there's no such field. I'm wondering if we should use `item.dynamic_annotation_report_design`'s `last_published` or something else?

@amoedoamorim we have a cached field `fact_check_published_on`, but it's not exposed in the GraphQL layer. That could be a good addition for the Check API `epic/cv2-3939-replace-table-view-with-cards` branch. You just need to declare a `fact_check_published_on` field in `app/graph/types/project_media_type.rb` and update the Relay file.

**Comment by brianfleming** [comment]
just a heads up @amoedoamorim pushed my way into your branch just to do some styling improvements, major, most notably a "checked" state style for the list items

**Comment by brianfleming** [comment]
@amoedoamorim and @caiosba I found another date issue to discuss.
It actually might be pre-existing, but wanted to flag to investigate by someone:
- Add a new media item but using the add item button
- When you see it in the list the Request Count is correctly 0
- However, the Last Requested date is populated by the current date. This is inaccurate since this media cluster was technically never requested, since the requests list is empty and count 0

Is this a "pulling the wrong data" issue in the cards, or a pre-existing incorrectly storing data problem?

**Comment by brianfleming** [comment]
> @amoedoamorim and @caiosba I found another date issue to discuss. It actually might be pre-existing, but wanted to flag to investigate by someone:
> 
> * Add a new media item but using the add item button
> * When you see it in the list the Request Count is correctly 0
> * However, the Last Requested date is populated by the current date. This is inaccurate since this media cluster was technically never requested, since the requests list is empty and count 0
> 
> Is this a "pulling the wrong data" issue in the cards, or a pre-existing incorrectly storing data problem?

For whats its worth, when we "fix" this. To match the designs of the new cards the request count of 0 should be displayed, but the bullet and request date "button" should be hidden (ie. the 0 state for the date)

**Comment by amoedoamorim** [comment]
@brianfleming my understanding is that we use the `last_seen` field to populate the Last Requested Date button/chip. I guess the way this value is computed is that initially equals `created_at`, then gets updated with new requests. But per your follow up note, a quick fix is simply not displaying that button if Requests Count === 0

**Comment by brianfleming** [comment]
> @brianfleming my understanding is that we use the `last_seen` field to populate the Last Requested Date button/chip. I guess the way this value is computed is that initially equals `created_at`, then gets updated with new requests. But per your follow up note, a quick fix is simply not displaying that button if Requests Count === 0

Ok, makes sense, we can hide based on count then 🔆

**Comment by amoedoamorim** [comment]
> @amoedoamorim we have a cached field fact_check_published_on, but it's not exposed in the GraphQL layer. That could be a good addition for the Check API epic/cv2-3939-replace-table-view-with-cards branch. You just need to declare a fact_check_published_on field in app/graph/types/project_media_type.rb and update the Relay file.

Just merged this to `develop` so the  `publishedAt` for cluster card is ready to go.

Fixed the Last Requested Date from the props passing to `ClusterCard` as well

**Comment by caiosba** [comment]
Just confirming what @amoedoamorim explained at https://github.com/meedan/check-web/pull/1973#issuecomment-2162985863 :+1: Thanks Alelas!

**Review by brianfleming — APPROVED** [review]

**Pull request merged**
