### PR TITLE
List styles more consistent

### PR DESCRIPTION
**Pull request by brianfleming**
## Description

While reviewing Articles epic progress i am making some improvements to remove older code and share more styles between lists for consistency.

Also rename some css imports to better see shared style use

Toolbar is an unnecessary import since its only used in one place

References: [CV2-4441](https://meedan.atlassian.net/browse/CV2-4441)

## Type of change

- [ ] Performance improvement and/or refactoring (non-breaking change that keeps existing functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Security mitigation or enhancement
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Automated test (add or update automated tests)

## How has this been tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can verify the changes. Please describe whether or not you implemented automated tests.

## Things to pay attention to during code review

To prepare to eventually move the Add Media button to the side navigation and get more consistent with the placement of the paging control, the Add Media button is now moved to the center position:

Screenshot 2024-06-28 at 11 43 52 AM

## Checklist

- [x] I have performed a self-review of my own code
- [x] I've made sure my branch is runnable and given good testing steps in the PR description
- [x] I considered secure coding practices when writing this code. Any security concerns are noted above.
- [x] I have commented my code in hard-to-understand areas, if any
- [ ] I have made needed changes to the README
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I implemented any new components, they are self-contained, their `propTypes` are declared and they use React Hooks and, if data-fetching is required, they use Relay Modern with fragment containers
- [ ] If my components involve user interaction - specifically button, text fields, or other inputs - I have added a [BEM-like class name](https://meedan.atlassian.net/wiki/spaces/ENG/pages/1327628289/Naming+conventions+for+interactive+elements) to the element that is interacted with
- [x] To the best of my knowledge, any new styles are applied according to the design system
- [ ] If I added a new external dependency, I included a rationale for doing so and an estimate of the change in bundle size (e.g., checked in https://bundlephobia.com/)

[CV2-4441]: https://meedan.atlassian.net/browse/CV2-4441?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by brianfleming** [comment]
Reviewers: anyone know why the linter step is failing? is says this fails: `The command "docker-compose exec web npm run linter" failed and exited with 137 during .`

but when I run that command locally everything appears normal.

**Comment by amoedoamorim** [comment]
> A 137 code is issued when a process is terminated externally because of its memory consumption.

@brianfleming

**Comment by brianfleming** [comment]
> > A 137 code is issued when a process is terminated externally because of its memory consumption.
> 
> @brianfleming

I knew it couldn't have been something I did @amoedoamorim ! 😅 
Is there something I should do?

**Comment by amoedoamorim** [comment]
Let's watch if that happens consistently. If so I guess we'll need to either make it run more efficiently or let it have more memory resources.

**Comment by brianfleming** [comment]
> Let's watch if that happens consistently. If so I guess we'll need to either make it run more efficiently or let it have more memory resources.

yeah, it looks like it happened on every push i made to this PR. is it related to maybe the video sim testing taking up too many resources? meaning its temporary problem?

**Comment by caiosba** [comment]
@brianfleming @amoedoamorim in many cases this is a misleading error from Docker - I've seen it happening when the frontend is not in sync with the backend w/r/t the GraphQL API. For example, Brian, if this Check Web branch was created from the articles epic branch, it will fail because it will use the develop branch for Check API which doesn't contain some of the needed GraphQL fields. If that's the case, I suggest you create a branch on Check API, from the articles epic branch, with the same name as this Check Web branch.

**Comment by brianfleming** [comment]
> @brianfleming @amoedoamorim in many cases this is a misleading error from Docker - I've seen it happening when the frontend is not in sync with the backend w/r/t the GraphQL API. For example, Brian, if this Check Web branch was created from the articles epic branch, it will fail because it will use the develop branch for Check API which doesn't contain some of the needed GraphQL fields. If that's the case, I suggest you create a branch on Check API, from the articles epic branch, with the same name as this Check Web branch.

Oh awesome answer. Thanks @caiosba that makes total sense. I will give that a try. This PR is mostly css and html changes, but it I want to try out what you suggest anyway!

**Comment by brianfleming** [comment]
And of course now there is a github outage for PRs!!

Anyway, @sarahkeh this is what is probably the case with your PR branch for editing, FYI, since it has the same linter error

**Comment by brianfleming** [comment]
@caiosba ftw! thanks, that allowed the tests to run for this branch

**Comment by brianfleming** [comment]
Pinging reviewers here for a friendly reminder

**Review by sarahkeh — APPROVED** [review]
Looks good, removing the Toolbar file makes sense, it's a relatively small addition to the SearchResults file and isn't used anywhere else.  I like that you were able to simplify the styles to avoid having to pass a class through as a prop.

**Pull request merged**
